import { Router, Request, Response, NextFunction } from 'express'
import { Pool, PoolClient } from 'pg'
import jwt from 'jsonwebtoken'
import bcrypt from 'bcryptjs'
import crypto from 'crypto'
import { onlineUserPredicate } from './presence'

interface AdminRequest extends Request { adminId?: string }
const int = (value: unknown, fallback: number, max = 100) => Math.min(max, Math.max(1, Number(value) || fallback))
const allowedSort = (value: unknown, allowed: string[], fallback: string) => allowed.includes(String(value)) ? String(value) : fallback

export function createAdminRouter(pool: Pool, jwtSecret: string) {
  const router = Router()
  const sendError = (res: Response, error: any, fallbackStatus = 500) => {
    const migrationRequired = error?.code === '42703' || error?.code === '42P01'
    return res.status(migrationRequired ? 503 : fallbackStatus).json({
      code: migrationRequired ? 'DATABASE_MIGRATION_REQUIRED' : 'ADMIN_BACKEND_ERROR',
      error: error?.message || 'Administration request failed',
    })
  }
  router.use(async (req: AdminRequest, res: Response, next: NextFunction) => {
    const header = req.headers.authorization
    if (!header?.startsWith('Bearer ')) return res.status(401).json({ error: 'Unauthorized', code: 'AUTH_REQUIRED' })
    try {
      const payload = jwt.verify(header.slice(7), jwtSecret) as { sub: string }
      const result = await pool.query("SELECT id FROM users WHERE id=$1 AND role='admin' AND deleted_at IS NULL", [payload.sub])
      if (!result.rows[0]) return res.status(403).json({ error: 'Administrator access required', code: 'ADMIN_REQUIRED' })
      req.adminId = payload.sub
      next()
    } catch (error: any) { return error?.code ? sendError(res,error) : res.status(401).json({ error: 'Invalid or expired token', code: 'AUTH_INVALID' }) }
  })

  const audit = async (db: Pool | PoolClient, req: AdminRequest, action: string, targetType: string, targetId?: string, details: object = {}) => {
    await db.query(`INSERT INTO admin_audit_logs(admin_id,action,target_type,target_id,details,ip)
      VALUES($1,$2,$3,$4,$5,$6)`, [req.adminId, action, targetType, targetId || null, JSON.stringify(details), req.ip || null])
  }
  const transaction = async <T>(fn: (db: PoolClient) => Promise<T>) => {
    const db = await pool.connect()
    try { await db.query('BEGIN'); const value = await fn(db); await db.query('COMMIT'); return value }
    catch (error) { await db.query('ROLLBACK'); throw error } finally { db.release() }
  }
  const safeUserColumns = 'id,email,username,display_name,bio,role,steam_id,steam_avatar,steam_profile_url,is_premium,vip_since,vip_expires_at,vip_method,points,experience,level,wins,losses,steam_verified,owns_hl1,vac_banned,game_banned,equipped_badge,equipped_frame,owned_badges,owned_frames,social_links,profile_visibility,show_online_status,created_at,last_seen,deleted_at'
  const safeUser = async(db:Pool|PoolClient,id:string)=>{
    const user=(await db.query(`SELECT ${safeUserColumns} FROM users WHERE id=$1`,[id])).rows[0]
    if(!user)return null
    user.activeBan=(await db.query("SELECT id,reason,ban_type,expires_at,created_at FROM bans WHERE user_id=$1 AND is_active AND (expires_at IS NULL OR expires_at>NOW()) ORDER BY created_at DESC LIMIT 1",[id])).rows[0]||null
    return user
  }

  router.get('/dashboard', async (_req, res) => {
    try {
      const [counts, registrations, matches, purchases] = await Promise.all([
        pool.query(`SELECT
          COUNT(*) FILTER (WHERE deleted_at IS NULL)::int total_users,
          COUNT(*) FILTER (WHERE ${onlineUserPredicate('users')})::int online_users,
          COUNT(*) FILTER (WHERE is_premium AND deleted_at IS NULL)::int premium_users,
          COUNT(*) FILTER (WHERE steam_id IS NOT NULL AND deleted_at IS NULL)::int steam_linked,
          COUNT(*) FILTER (WHERE steam_verified AND deleted_at IS NULL)::int steam_verified,
          COUNT(*) FILTER (WHERE owns_hl1 AND deleted_at IS NULL)::int owns_hl1 FROM users`),
        pool.query(`SELECT series_day::date AS day, COUNT(u.id)::int AS value
          FROM generate_series(CURRENT_DATE - INTERVAL '13 days', CURRENT_DATE, INTERVAL '1 day') AS series(series_day)
          LEFT JOIN users u ON u.created_at::date = series_day::date
          GROUP BY series_day ORDER BY series_day`),
        pool.query(`SELECT series_day::date AS day, COUNT(m.id)::int AS value
          FROM generate_series(CURRENT_DATE - INTERVAL '13 days', CURRENT_DATE, INTERVAL '1 day') AS series(series_day)
          LEFT JOIN matches m ON m.created_at::date = series_day::date
          GROUP BY series_day ORDER BY series_day`),
        pool.query(`SELECT COUNT(*) FILTER(WHERE status IN ('pending','in_progress'))::int running_matches,
          (SELECT COUNT(*)::int FROM queue_entries) current_queue,
          (SELECT COUNT(*)::int FROM game_servers WHERE status='online') online_servers,
          (SELECT COUNT(*)::int FROM tournaments WHERE status IN ('registration','in_progress')) active_tournaments,
          (SELECT COUNT(*)::int FROM reports WHERE status='pending') reports_waiting,
          (SELECT COUNT(*)::int FROM bans WHERE is_active AND (expires_at IS NULL OR expires_at>NOW())) banned_players FROM matches`)
      ])
      res.json({ cards: { ...counts.rows[0], ...purchases.rows[0] }, charts: { registrations: registrations.rows, matches: matches.rows } })
    } catch (e: any) { sendError(res,e) }
  })

  router.get('/users', async (req, res) => {
    const page=int(req.query.page,1), limit=int(req.query.limit,25), sort=allowedSort(req.query.sort,['created_at','username','email','points','experience','last_seen'],'created_at')
    const direction=String(req.query.direction).toLowerCase()==='asc'?'ASC':'DESC', q=String(req.query.q||'').trim()
    const includeDeleted=String(req.query.includeDeleted)==='true'
    const where=`${includeDeleted?'TRUE':'deleted_at IS NULL'} AND ($1='' OR username ILIKE '%'||$1||'%' OR email ILIKE '%'||$1||'%' OR steam_id ILIKE '%'||$1||'%' OR display_name ILIKE '%'||$1||'%')`
    try { const [rows,count]=await Promise.all([
      pool.query(`SELECT users.id,email,username,display_name,role,steam_id,steam_avatar,is_premium,vip_method,vip_expires_at,points,experience,level,wins,losses,steam_verified,owns_hl1,vac_banned,game_banned,created_at,last_seen,deleted_at,(${onlineUserPredicate('users')}) is_online,(SELECT jsonb_build_object('id',b.id,'reason',b.reason,'expires_at',b.expires_at) FROM bans b WHERE b.user_id=users.id AND b.is_active AND (b.expires_at IS NULL OR b.expires_at>NOW()) ORDER BY b.created_at DESC LIMIT 1) active_ban FROM users WHERE ${where} ORDER BY ${sort} ${direction} LIMIT $2 OFFSET $3`,[q,limit,(page-1)*limit]),
      pool.query(`SELECT COUNT(*)::int total FROM users WHERE ${where}`,[q])]); res.json({items:rows.rows,total:count.rows[0].total,page,limit})
    } catch(e:any){sendError(res,e)}
  })
  router.post('/users',async(req:AdminRequest,res)=>{try{const {email,username,password,role='user'}=req.body;if(typeof email!=='string'||typeof username!=='string'||typeof password!=='string')return res.status(400).json({error:'Email, username and password are required'});if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});if(!['user','admin'].includes(role))return res.status(400).json({error:'Invalid role'});const user=await transaction(async db=>{const hash=await bcrypt.hash(password,12);const r=await db.query('INSERT INTO users(email,username,password_hash,role) VALUES(lower($1),$2,$3,$4) RETURNING id,email,username,role,created_at',[email.trim(),username.trim(),hash,role]);await audit(db,req,'user.create','user',r.rows[0].id,{email:r.rows[0].email,username:r.rows[0].username,role});return r.rows[0]});res.status(201).json({user})}catch(e:any){res.status(e.code==='23505'?409:400).json({error:e.code==='23505'?'Email or username already exists':e.message})}})
  router.get('/users/:id', async(req,res)=>{try{const user=await safeUser(pool,req.params.id);if(!user)return res.status(404).json({error:'User not found',code:'USER_NOT_FOUND'});const optional=async(sql:string)=>{try{return(await pool.query(sql,[req.params.id])).rows}catch{return[]}};const [loginHistory,matches,reports,auditHistory]=await Promise.all([
    optional('SELECT method,success,ip,created_at FROM login_history WHERE user_id=$1 ORDER BY created_at DESC LIMIT 25'),
    optional('SELECT id,player1_id,player2_id,winner_id,status,score_p1,score_p2,created_at FROM matches WHERE player1_id=$1 OR player2_id=$1 ORDER BY created_at DESC LIMIT 25'),
    optional('SELECT id,reporter_id,reason,status,created_at FROM reports WHERE reported_id=$1 ORDER BY created_at DESC LIMIT 25'),
    optional("SELECT action,details,created_at FROM admin_audit_logs WHERE target_type='user' AND target_id=$1 ORDER BY created_at DESC LIMIT 25")]);res.json({user,loginHistory,matches,reports,auditHistory})}catch(e:any){sendError(res,e)}})

  router.patch('/users/:id', async(req:AdminRequest,res)=>{
    const fields:Record<string,string>={username:'username',displayName:'display_name',email:'email',role:'role',bio:'bio',points:'points',experience:'experience',level:'level',wins:'wins',losses:'losses',isPremium:'is_premium',vipExpiresAt:'vip_expires_at',vipMethod:'vip_method',profileVisibility:'profile_visibility',showOnlineStatus:'show_online_status'}
    const entries=Object.entries(req.body).filter(([k])=>fields[k]); if(!entries.length)return res.status(400).json({error:'No supported fields'})
    if(req.body.email!==undefined&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(req.body.email)))return res.status(400).json({error:'Invalid email'})
    if(req.body.username!==undefined&&!/^[A-Za-z0-9_-]{3,32}$/.test(String(req.body.username)))return res.status(400).json({error:'Username must be 3-32 characters using letters, numbers, underscore or hyphen'})
    if(req.body.role!==undefined&&!['user','admin'].includes(req.body.role))return res.status(400).json({error:'Invalid role'})
    if(req.body.vipMethod!==undefined&&req.body.vipMethod!==null&&!['points','payment'].includes(req.body.vipMethod))return res.status(400).json({error:'Invalid VIP method'})
    if(req.body.profileVisibility!==undefined&&!['public','friends','private'].includes(req.body.profileVisibility))return res.status(400).json({error:'Invalid profile visibility'})
    if(req.body.showOnlineStatus!==undefined&&typeof req.body.showOnlineStatus!=='boolean')return res.status(400).json({error:'showOnlineStatus must be boolean'})
    for(const key of ['points','experience','level','wins','losses'])if(req.body[key]!==undefined&&(!Number.isInteger(Number(req.body[key]))||Number(req.body[key])<0))return res.status(400).json({error:`${key} must be a non-negative integer`})
    try{const user=await transaction(async db=>{const before=(await db.query(`SELECT ${safeUserColumns} FROM users WHERE id=$1 FOR UPDATE`,[req.params.id])).rows[0];if(!before)throw new Error('User not found');if(req.body.role==='user'&&before.role==='admin'){const count=await db.query("SELECT COUNT(*)::int total FROM users WHERE role='admin' AND deleted_at IS NULL");if(count.rows[0].total<=1)throw new Error('Cannot demote the final administrator')}const normalized=entries.map(([key,value])=>[key,key==='email'?String(value).trim().toLowerCase():key==='username'?String(value).trim():value] as [string,any]);const vals=normalized.map(([,v])=>v);const assignments=normalized.map(([k],i)=>`${fields[k]}=$${i+1}`).join(',');await db.query(`UPDATE users SET ${assignments},updated_at=NOW() WHERE id=$${vals.length+1}`,[...vals,req.params.id]);const after=await safeUser(db,req.params.id);await audit(db,req,'user.update','user',req.params.id,{before,after,reason:req.body.reason||null});return after});res.json({user})}catch(e:any){res.status(e.code==='23505'?409:e.message==='User not found'?404:400).json({error:e.code==='23505'?'Email or username already exists':e.message})}
  })
  const setUserDeactivated=async(req:AdminRequest,res:Response,deactivate:boolean)=>{const reason=typeof req.body?.reason==='string'?req.body.reason.trim():'';if(!reason)return res.status(400).json({error:'A reason is required'});try{const user=await transaction(async db=>{const before=(await db.query(`SELECT ${safeUserColumns} FROM users WHERE id=$1 FOR UPDATE`,[req.params.id])).rows[0];if(!before)throw new Error('User not found');if(deactivate&&before.deleted_at)throw new Error('User is already deactivated');if(!deactivate&&!before.deleted_at)throw new Error('User is already active');if(deactivate&&req.params.id===req.adminId&&!(req.body.confirmSelf===true&&req.body.confirmSelfAgain===true))throw new Error('Self-deactivation requires two explicit confirmations');if(deactivate&&before.role==='admin'){const count=await db.query("SELECT COUNT(*)::int total FROM users WHERE role='admin' AND deleted_at IS NULL");if(count.rows[0].total<=1)throw new Error('Cannot deactivate the final administrator')}await db.query(`UPDATE users SET deleted_at=${deactivate?'NOW()':'NULL'},updated_at=NOW() WHERE id=$1`,[req.params.id]);const after=await safeUser(db,req.params.id);await audit(db,req,deactivate?'user.deactivate':'user.restore','user',req.params.id,{before,after,reason,self:req.params.id===req.adminId});return after});res.json({user})}catch(e:any){res.status(e.message==='User not found'?404:400).json({error:e.message})}}
  router.post('/users/:id/deactivate',(req:AdminRequest,res)=>setUserDeactivated(req,res,true))
  router.post('/users/:id/restore',(req:AdminRequest,res)=>setUserDeactivated(req,res,false))
  router.delete('/users/:id/permanent',async(req:AdminRequest,res)=>{const reason=typeof req.body?.reason==='string'?req.body.reason.trim():'';const confirmation=typeof req.body?.confirmation==='string'?req.body.confirmation.trim():'';if(!reason)return res.status(400).json({error:'A reason is required'});try{const deletedUser=await transaction(async db=>{const before=(await db.query(`SELECT ${safeUserColumns} FROM users WHERE id=$1 FOR UPDATE`,[req.params.id])).rows[0];if(!before)throw new Error('User not found');if(confirmation!=='DELETE'&&confirmation!==before.username)throw new Error('Type the username or DELETE to confirm permanent deletion');const isSelf=req.params.id===req.adminId;if(isSelf&&!(req.body.confirmSelf===true&&req.body.confirmSelfAgain===true))throw new Error('Self-deletion requires two explicit confirmations');if(before.role==='admin'){const remaining=await db.query("SELECT COUNT(*)::int total FROM users WHERE role='admin' AND deleted_at IS NULL AND id<>$1",[req.params.id]);if(remaining.rows[0].total<1)throw new Error('Cannot permanently delete the final administrator')}await audit(db,req,'user.permanent_delete','user',req.params.id,{user:{id:before.id,username:before.username,email:before.email,role:before.role,deleted_at:before.deleted_at},reason,self:isSelf});await db.query('DELETE FROM users WHERE id=$1',[req.params.id]);return{id:before.id,username:before.username}});res.json({success:true,deletedUser})}catch(e:any){res.status(e.message==='User not found'?404:400).json({error:e.message})}})
  router.post('/users/:id/action',async(req:AdminRequest,res)=>{const {action,amount,reason,durationMinutes,itemId,expiresAt,vipMethod}=req.body;try{const result=await transaction(async db=>{const before=(await db.query(`SELECT ${safeUserColumns} FROM users WHERE id=$1 FOR UPDATE`,[req.params.id])).rows[0];if(!before)throw new Error('User not found');const reasonText=typeof reason==='string'?reason.trim():'';if(['give_points','remove_points','set_points','grant_vip','remove_vip','grant_badge','remove_badge','grant_frame','remove_frame','equip_badge','equip_frame','unequip_badge','unequip_frame','ban','unban','delete','restore'].includes(action)&&!reasonText)throw new Error('A reason is required');
    if(['give_points','remove_points','set_points'].includes(action)){const n=Number(amount);if(!Number.isInteger(n)||n<0)throw new Error('Point amount must be a non-negative integer');if(action!=='set_points'&&n===0)throw new Error('Point amount must be greater than zero');if(action==='set_points')await db.query('UPDATE users SET points=$1 WHERE id=$2',[n,req.params.id]);else await db.query(`UPDATE users SET points=GREATEST(0,points${action==='give_points'?'+':'-'}$1) WHERE id=$2`,[n,req.params.id])}
    else if(action==='grant_vip'){if(vipMethod!==undefined&&!['points','payment'].includes(vipMethod))throw new Error('Invalid VIP method');if(expiresAt&&Number.isNaN(Date.parse(expiresAt)))throw new Error('Invalid VIP expiration');await db.query('UPDATE users SET is_premium=true,vip_since=COALESCE(vip_since,NOW()),vip_expires_at=$1::timestamptz,vip_method=$2 WHERE id=$3',[expiresAt||null,vipMethod||'points',req.params.id])}
    else if(action==='remove_vip')await db.query('UPDATE users SET is_premium=false,vip_expires_at=NULL,vip_method=NULL WHERE id=$1',[req.params.id])
    else if(['grant_badge','remove_badge','grant_frame','remove_frame','equip_badge','equip_frame','unequip_badge','unequip_frame'].includes(action)){const isBadge=action.includes('badge'),owned=isBadge?'owned_badges':'owned_frames',equipped=isBadge?'equipped_badge':'equipped_frame',catalog=isBadge?'badges':'frames';if(action.startsWith('unequip'))await db.query(`UPDATE users SET ${equipped}=NULL WHERE id=$1`,[req.params.id]);else{if(!itemId)throw new Error('Catalog item is required');if(!(await db.query(`SELECT id FROM ${catalog} WHERE id=$1`,[itemId])).rows[0])throw new Error('Catalog item not found');if(action.startsWith('grant'))await db.query(`UPDATE users SET ${owned}=array_append(COALESCE(${owned},'{}'::text[]),$1) WHERE id=$2 AND NOT($1=ANY(COALESCE(${owned},'{}'::text[])))`,[itemId,req.params.id]);else if(action.startsWith('remove'))await db.query(`UPDATE users SET ${owned}=array_remove(COALESCE(${owned},'{}'::text[]),$1),${equipped}=CASE WHEN ${equipped}=$1 THEN NULL ELSE ${equipped} END WHERE id=$2`,[itemId,req.params.id]);else{const r=await db.query(`UPDATE users SET ${equipped}=$1 WHERE id=$2 AND $1=ANY(COALESCE(${owned},'{}'::text[])) RETURNING id`,[itemId,req.params.id]);if(!r.rows[0])throw new Error('Item is not owned')}}}
    else if(action==='mute')await db.query("INSERT INTO user_mutes(user_id,reason,issued_by,expires_at) VALUES($1,$2,$3,CASE WHEN $4::int IS NULL THEN NULL ELSE NOW()+($4||' minutes')::interval END)",[req.params.id,reason||'Administrative mute',req.adminId,durationMinutes||null])
    else if(action==='unmute')await db.query('UPDATE user_mutes SET is_active=false,lifted_at=NOW() WHERE user_id=$1 AND is_active=true',[req.params.id])
    else if(action==='steam_override'){const {steamVerified,ownsHL1,vacBanned,gameBanned}=req.body;if([steamVerified,ownsHL1,vacBanned,gameBanned].some(v=>v!==undefined&&typeof v!=='boolean'))throw new Error('Steam override fields must be boolean');await db.query('UPDATE users SET steam_verified=COALESCE($1,steam_verified),owns_hl1=COALESCE($2,owns_hl1),vac_banned=COALESCE($3,vac_banned),game_banned=COALESCE($4,game_banned) WHERE id=$5',[steamVerified??null,ownsHL1??null,vacBanned??null,gameBanned??null,req.params.id])}
    else if(action==='ban'){if(expiresAt&&Number.isNaN(Date.parse(expiresAt)))throw new Error('Invalid ban expiration');if(expiresAt&&new Date(expiresAt)<=new Date())throw new Error('Ban expiration must be in the future');await db.query("UPDATE bans SET is_active=false,lifted_at=NOW() WHERE user_id=$1 AND is_active=true",[req.params.id]);await db.query("INSERT INTO bans(user_id,reason,duration_minutes,expires_at,issued_by,ban_type) VALUES($1,$2,CASE WHEN $3::timestamptz IS NULL THEN NULL ELSE CEIL(EXTRACT(EPOCH FROM($3::timestamptz-NOW()))/60)::int END,$3,$4,'platform')",[req.params.id,reasonText,expiresAt||null,req.adminId])}
    else if(action==='unban')await db.query('UPDATE bans SET is_active=false,lifted_at=NOW() WHERE user_id=$1 AND is_active=true',[req.params.id])
    else if(action==='reset_password'){const temporary=crypto.randomBytes(12).toString('base64url');await db.query('UPDATE users SET password_hash=$1 WHERE id=$2',[await bcrypt.hash(temporary,12),req.params.id]);await audit(db,req,action,'user',req.params.id);return{temporaryPassword:temporary}}
    else if(action==='delete'){const target=await db.query('SELECT role FROM users WHERE id=$1 FOR UPDATE',[req.params.id]);if(target.rows[0]?.role==='admin'){const count=await db.query("SELECT COUNT(*)::int total FROM users WHERE role='admin' AND deleted_at IS NULL");if(count.rows[0].total<=1)throw new Error('Cannot delete the final administrator')}await db.query('UPDATE users SET deleted_at=NOW() WHERE id=$1',[req.params.id])}
    else if(action==='restore')await db.query('UPDATE users SET deleted_at=NULL WHERE id=$1',[req.params.id])
    else throw new Error('Unsupported action');const after=await safeUser(db,req.params.id);await audit(db,req,`user.${action}`,'user',req.params.id,{before,after,amount,reason:reasonText,durationMinutes,itemId,expiresAt:expiresAt||null,vipMethod:vipMethod||null});return{user:after}});res.json(result)}catch(e:any){res.status(e.message==='User not found'?404:400).json({error:e.message})}})

  const safeServerColumns="id,game_id,game,region,name,ip_address AS public_host,port,max_slots,status,current_match_id,created_at,updated_at,(rcon_password IS NOT NULL AND rcon_password<>'') AS has_rcon"
  const safeServer=async(db:Pool|PoolClient,id:string,lock=false)=>(await db.query(`SELECT ${safeServerColumns} FROM game_servers WHERE id=$1${lock?' FOR UPDATE':''}`,[id])).rows[0]||null
  router.get('/servers',async(_req,res)=>{try{res.json({items:(await pool.query(`SELECT ${safeServerColumns} FROM game_servers ORDER BY created_at DESC`)).rows})}catch(e:any){sendError(res,e)}})
  router.get('/servers/:id',async(req,res)=>{try{const [server,matches]=await Promise.all([safeServer(pool,req.params.id),pool.query("SELECT id,game_id,status,player1_id,player2_id,selected_map,created_at FROM matches WHERE status IN ('pending','in_progress') AND (server_id IS NULL OR server_id=$1) ORDER BY created_at DESC",[req.params.id])]);if(!server)return res.status(404).json({error:'Server not found'});res.json({server,activeMatches:matches.rows})}catch(e:any){sendError(res,e)}})
  router.post('/servers',async(req:AdminRequest,res)=>{try{const {game='Half-Life 1',gameId='hl1',region,name,ip,port,slots,status='offline'}=req.body;if(gameId!=='hl1')return res.status(400).json({error:'Unsupported game ID'});if(!['online','offline','maintenance'].includes(status))return res.status(400).json({error:'Invalid initial server status'});if(!String(region||'').trim()||!String(name||'').trim()||!String(ip||'').trim())return res.status(400).json({error:'Region, name and public host are required'});if(!Number.isInteger(Number(port))||Number(port)<1||Number(port)>65535)return res.status(400).json({error:'Port must be between 1 and 65535'});if(!Number.isInteger(Number(slots))||Number(slots)<1)return res.status(400).json({error:'Slots must be a positive integer'});const server=await transaction(async db=>{if((await db.query('SELECT id FROM game_servers WHERE ip_address=$1 AND port=$2',[String(ip).trim(),Number(port)])).rows[0])throw new Error('A server already uses that public host and port');const r=await db.query('INSERT INTO game_servers(game,game_id,region,name,ip,ip_address,port,slots,max_slots,status) VALUES($1,$2,$3,$4,$5,$5,$6,$7,$7,$8) RETURNING id',[String(game).trim(),gameId,String(region).trim(),String(name).trim(),String(ip).trim(),Number(port),Number(slots),status]);const saved=await safeServer(db,r.rows[0].id);await audit(db,req,'server.create','server',r.rows[0].id,{after:saved});return saved});res.status(201).json({server})}catch(e:any){res.status(e.code==='23505'?409:400).json({error:e.code==='23505'?'A server already uses that public host and port':e.message})}})
  router.patch('/servers/:id',async(req:AdminRequest,res)=>{const {gameId,game,region,name,publicHost,port,maxSlots}=req.body;if([gameId,game,region,name,publicHost,port,maxSlots].every(v=>v===undefined))return res.status(400).json({error:'No supported fields'});if(gameId!==undefined&&gameId!=='hl1')return res.status(400).json({error:'Unsupported game ID'});for(const [key,value] of [['game',game],['region',region],['name',name],['publicHost',publicHost]] as [string,any][])if(value!==undefined&&!String(value).trim())return res.status(400).json({error:`${key} cannot be empty`});if(port!==undefined&&(!Number.isInteger(Number(port))||Number(port)<1||Number(port)>65535))return res.status(400).json({error:'Port must be between 1 and 65535'});if(maxSlots!==undefined&&(!Number.isInteger(Number(maxSlots))||Number(maxSlots)<1))return res.status(400).json({error:'Max slots must be a positive integer'});try{const server=await transaction(async db=>{const before=await safeServer(db,req.params.id);if(!before)throw new Error('Server not found');await db.query('SELECT id FROM game_servers WHERE id=$1 FOR UPDATE',[req.params.id]);const host=publicHost===undefined?before.public_host:String(publicHost).trim(),nextPort=port===undefined?before.port:Number(port);const conflict=(await db.query('SELECT id FROM game_servers WHERE ip_address=$1 AND port=$2 AND id<>$3',[host,nextPort,req.params.id])).rows[0];if(conflict)throw new Error('A server already uses that public host and port');await db.query('UPDATE game_servers SET game_id=COALESCE($1,game_id),game=COALESCE($2,game),region=COALESCE($3,region),name=COALESCE($4,name),ip_address=$5,ip=$5,port=$6,max_slots=COALESCE($7,max_slots),slots=COALESCE($7,slots),updated_at=NOW() WHERE id=$8',[gameId??null,game===undefined?null:String(game).trim(),region===undefined?null:String(region).trim(),name===undefined?null:String(name).trim(),host,nextPort,maxSlots===undefined?null:Number(maxSlots),req.params.id]);const after=await safeServer(db,req.params.id);await audit(db,req,'server.update','server',req.params.id,{before,after});return after});res.json({server})}catch(e:any){res.status(e.message==='Server not found'?404:400).json({error:e.message})}})
  router.post('/servers/:id/status',async(req:AdminRequest,res)=>{const {status}=req.body;if(!['online','offline','in_use','maintenance'].includes(status))return res.status(400).json({error:'Invalid server status'});try{const server=await transaction(async db=>{const before=await safeServer(db,req.params.id);if(!before)throw new Error('Server not found');if(status==='in_use'&&!before.current_match_id)throw new Error('Assign an active match before setting in_use');if(before.current_match_id&&status!=='in_use')throw new Error('Unassign the current match before changing this status');await db.query('UPDATE game_servers SET status=$1,updated_at=NOW() WHERE id=$2',[status,req.params.id]);const after=await safeServer(db,req.params.id);await audit(db,req,'server.status','server',req.params.id,{before,after});return after});res.json({server})}catch(e:any){res.status(e.message==='Server not found'?404:400).json({error:e.message})}})
  router.post('/servers/:id/assign-match',async(req:AdminRequest,res)=>{const {matchId}=req.body;if(!matchId)return res.status(400).json({error:'matchId is required'});try{const server=await transaction(async db=>{const before=await safeServer(db,req.params.id);if(!before)throw new Error('Server not found');await db.query('SELECT id FROM game_servers WHERE id=$1 FOR UPDATE',[req.params.id]);if(before.current_match_id&&before.current_match_id!==matchId)throw new Error('Server is already assigned; unassign it first');const match=(await db.query("SELECT id,game_id,status,server_id FROM matches WHERE id=$1 FOR UPDATE",[matchId])).rows[0];if(!match)throw new Error('Match not found');if(!['pending','in_progress'].includes(match.status))throw new Error('Only active matches can be assigned');if(match.game_id!==before.game_id)throw new Error('Server and match game IDs do not match');if(match.server_id&&match.server_id!==req.params.id)throw new Error('Match is already assigned to another server');await db.query("UPDATE game_servers SET current_match_id=$1,status='in_use',updated_at=NOW() WHERE id=$2",[matchId,req.params.id]);await db.query('UPDATE matches SET server_id=$1 WHERE id=$2',[req.params.id,matchId]);const after=await safeServer(db,req.params.id);await audit(db,req,'server.assign_match','server',req.params.id,{before,after,matchId});return after});res.json({server})}catch(e:any){res.status(['Server not found','Match not found'].includes(e.message)?404:400).json({error:e.message})}})
  router.post('/servers/:id/unassign-match',async(req:AdminRequest,res)=>{const {status}=req.body;if(!['online','offline'].includes(status))return res.status(400).json({error:'Unassigned status must be online or offline'});try{const server=await transaction(async db=>{const before=await safeServer(db,req.params.id);if(!before)throw new Error('Server not found');await db.query('SELECT id FROM game_servers WHERE id=$1 FOR UPDATE',[req.params.id]);if(!before.current_match_id)throw new Error('Server has no assigned match');await db.query('UPDATE matches SET server_id=NULL WHERE id=$1 AND server_id=$2',[before.current_match_id,req.params.id]);await db.query('UPDATE game_servers SET current_match_id=NULL,status=$1,updated_at=NOW() WHERE id=$2',[status,req.params.id]);const after=await safeServer(db,req.params.id);await audit(db,req,'server.unassign_match','server',req.params.id,{before,after,matchId:before.current_match_id});return after});res.json({server})}catch(e:any){res.status(e.message==='Server not found'?404:400).json({error:e.message})}})
  router.delete('/servers/:id',async(req:AdminRequest,res)=>{try{const server=await transaction(async db=>{const before=await safeServer(db,req.params.id);if(!before)throw new Error('Server not found');await db.query('SELECT id FROM game_servers WHERE id=$1 FOR UPDATE',[req.params.id]);const assigned=(await db.query("SELECT id FROM matches WHERE server_id=$1 AND status IN ('pending','in_progress') LIMIT 1 FOR UPDATE",[req.params.id])).rows[0];if(before.current_match_id||assigned)throw new Error('Unassign the active match before deleting this server');await db.query('UPDATE matches SET server_id=NULL WHERE server_id=$1',[req.params.id]);await db.query('DELETE FROM game_servers WHERE id=$1',[req.params.id]);await audit(db,req,'server.delete','server',req.params.id,{before});return before});res.json({server,deleted:true})}catch(e:any){res.status(e.message==='Server not found'?404:400).json({error:e.message})}})

  router.get('/queue',async(_req,res)=>{try{res.json({items:(await pool.query('SELECT q.*,u.username,u.display_name,u.steam_avatar,EXTRACT(EPOCH FROM(NOW()-q.joined_at))::int waiting_seconds FROM queue_entries q JOIN users u ON u.id=q.user_id WHERE u.deleted_at IS NULL ORDER BY q.joined_at')).rows})}catch(e:any){sendError(res,e)}})
  router.delete('/queue/:userId',async(req:AdminRequest,res)=>{try{await transaction(async db=>{await db.query('DELETE FROM queue_entries WHERE user_id=$1',[req.params.userId]);await audit(db,req,'queue.remove','user',req.params.userId)});res.json({ok:true})}catch(e:any){res.status(400).json({error:e.message})}})
  router.delete('/queue',async(req:AdminRequest,res)=>{try{const userIds=Array.isArray(req.body?.userIds)?req.body.userIds:[];const removed=await transaction(async db=>{const r=userIds.length?await db.query('DELETE FROM queue_entries WHERE user_id=ANY($1::uuid[]) RETURNING user_id',[userIds]):await db.query('DELETE FROM queue_entries RETURNING user_id');await audit(db,req,userIds.length?'queue.clear_selected':'queue.clear_all','queue',undefined,{userIds,removed:r.rowCount});return r.rowCount||0});res.json({removed})}catch(e:any){res.status(400).json({error:e.message})}})
  router.post('/queue/force-match',async(req:AdminRequest,res)=>{try{const userIds=Array.isArray(req.body?.userIds)?req.body.userIds:[];if(userIds.length!==2||userIds[0]===userIds[1])return res.status(400).json({error:'Exactly two distinct queued users are required'});const match=await transaction(async db=>{const queued=await db.query(`SELECT q.*,u.steam_verified,u.owns_hl1,u.vac_banned,u.game_banned,u.deleted_at FROM queue_entries q JOIN users u ON u.id=q.user_id WHERE q.user_id=ANY($1::uuid[]) FOR UPDATE`,[userIds]);if(queued.rowCount!==2)throw new Error('Both users must still be queued');for(const row of queued.rows)if(row.deleted_at||!row.steam_verified||!row.owns_hl1||row.vac_banned||row.game_banned)throw new Error('A selected user is not eligible for matchmaking');if(queued.rows[0].game_mode!==queued.rows[1].game_mode)throw new Error('Selected users must have the same game mode');const common=(queued.rows[0].selected_maps||[]).filter((map:string)=>(queued.rows[1].selected_maps||[]).includes(map));if(!common.length)throw new Error('Selected users have no common map');const r=await db.query(`INSERT INTO matches(match_type,game_mode,player1_id,player2_id,maps,selected_map,status,started_at) VALUES($1,$1,$2,$3,$4,$5,'in_progress',NOW()) RETURNING *`,[queued.rows[0].game_mode,userIds[0],userIds[1],common,common[0]]);await db.query('DELETE FROM queue_entries WHERE user_id=ANY($1::uuid[])',[userIds]);await audit(db,req,'queue.force_match','match',r.rows[0].id,{userIds,selectedMap:common[0]});return r.rows[0]});res.status(201).json({match})}catch(e:any){res.status(400).json({error:e.message})}})
  router.get('/matches',async(_req,res)=>{try{res.json({items:(await pool.query(`SELECT m.*,p1.username player1_username,p2.username player2_username FROM matches m LEFT JOIN users p1 ON p1.id=m.player1_id LEFT JOIN users p2 ON p2.id=m.player2_id ORDER BY m.created_at DESC LIMIT 200`)).rows})}catch(e:any){sendError(res,e)}})
  router.patch('/matches/:id',async(req:AdminRequest,res)=>{const {status,scoreP1,scoreP2,winnerId,serverId,selectedMap}=req.body;if(status!==undefined&&!['pending','completed','cancelled','in_progress'].includes(status))return res.status(400).json({error:'Invalid status'});if(scoreP1!==undefined&&(!Number.isInteger(Number(scoreP1))||Number(scoreP1)<0))return res.status(400).json({error:'Invalid player one score'});if(scoreP2!==undefined&&(!Number.isInteger(Number(scoreP2))||Number(scoreP2)<0))return res.status(400).json({error:'Invalid player two score'});if([status,scoreP1,scoreP2,winnerId,serverId,selectedMap].every(value=>value===undefined))return res.status(400).json({error:'No supported fields'});try{const match=await transaction(async db=>{const current=await db.query('SELECT * FROM matches WHERE id=$1 FOR UPDATE',[req.params.id]);if(!current.rows[0])throw new Error('Match not found');if(winnerId!==undefined&&winnerId!==null&&![current.rows[0].player1_id,current.rows[0].player2_id].includes(winnerId))throw new Error('Winner must be a match participant');if(selectedMap!==undefined&&!(current.rows[0].maps||[]).includes(selectedMap))throw new Error('Selected map is not valid for this match');if(serverId!==undefined){await db.query("UPDATE game_servers SET current_match_id=NULL,status=CASE WHEN status='in_use' THEN 'online' ELSE status END WHERE current_match_id=$1",[req.params.id]);if(serverId){const server=(await db.query('SELECT id FROM game_servers WHERE id=$1 FOR UPDATE',[serverId])).rows[0];if(!server)throw new Error('Server not found');await db.query("UPDATE game_servers SET current_match_id=$1,status='in_use',updated_at=NOW() WHERE id=$2",[req.params.id,serverId])}}const r=await db.query(`UPDATE matches SET status=COALESCE($1,status),score_p1=COALESCE($2,score_p1),score_p2=COALESCE($3,score_p2),winner_id=CASE WHEN $4::text='__unchanged__' THEN winner_id ELSE NULLIF($4,'')::uuid END,server_id=CASE WHEN $5::text='__unchanged__' THEN server_id ELSE NULLIF($5,'')::uuid END,selected_map=COALESCE($6,selected_map),completed_at=CASE WHEN $1 IN ('completed','cancelled') THEN NOW() WHEN $1 IN ('pending','in_progress') THEN NULL ELSE completed_at END WHERE id=$7 RETURNING *`,[status??null,scoreP1??null,scoreP2??null,winnerId===undefined?'__unchanged__':winnerId??'',serverId===undefined?'__unchanged__':serverId??'',selectedMap??null,req.params.id]);if(status==='completed'||status==='cancelled')await db.query("UPDATE game_servers SET current_match_id=NULL,status=CASE WHEN status='in_use' THEN 'online' ELSE status END WHERE current_match_id=$1",[req.params.id]);await audit(db,req,'match.update','match',req.params.id,{before:current.rows[0],after:r.rows[0],reason:req.body.reason||null});return r.rows[0]});res.json({match})}catch(e:any){res.status(400).json({error:e.message})}})
  router.get('/tournaments',async(_req,res)=>{try{res.json({items:(await pool.query('SELECT * FROM tournaments ORDER BY created_at DESC')).rows})}catch(e:any){sendError(res,e)}})
  router.post('/tournaments',async(req:AdminRequest,res)=>{try{const {id,name,description='',tournamentType='single-elimination',gameMode='classic-deathmatch',maxParticipants=16,entryFeePoints=0,prizePoolPoints=0,startDate}=req.body;if(!id||!name)return res.status(400).json({error:'Tournament ID and name are required'});const tournament=await transaction(async db=>{const r=await db.query(`INSERT INTO tournaments(id,name,description,tournament_type,game_mode,max_participants,entry_fee_points,prize_pool_points,start_date,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'registration') RETURNING *`,[String(id).trim(),String(name).trim(),description,tournamentType,gameMode,Number(maxParticipants),Number(entryFeePoints),Number(prizePoolPoints),startDate||null]);await audit(db,req,'tournament.create','tournament',r.rows[0].id,{name:r.rows[0].name});return r.rows[0]});res.status(201).json({tournament})}catch(e:any){res.status(e.code==='23505'?409:400).json({error:e.code==='23505'?'Tournament ID already exists':e.message})}})
  router.get('/tournaments/:id',async(req,res)=>{try{const [tournament,participants]=await Promise.all([pool.query('SELECT * FROM tournaments WHERE id=$1',[req.params.id]),pool.query('SELECT tp.*,u.username,u.display_name FROM tournament_participants tp JOIN users u ON u.id=tp.user_id WHERE tp.tournament_id=$1 ORDER BY tp.registered_at',[req.params.id])]);if(!tournament.rows[0])return res.status(404).json({error:'Tournament not found'});res.json({tournament:tournament.rows[0],participants:participants.rows})}catch(e:any){sendError(res,e)}})
  router.patch('/tournaments/:id',async(req:AdminRequest,res)=>{const fields:Record<string,string>={name:'name',description:'description',status:'status',maxParticipants:'max_participants',entryFeePoints:'entry_fee_points',prizePoolPoints:'prize_pool_points',prize1st:'prize_1st',prize2nd:'prize_2nd',prize3rd:'prize_3rd',startDate:'start_date',endDate:'end_date',registrationDeadline:'registration_deadline',requiresVip:'requires_vip'};const entries=Object.entries(req.body).filter(([key])=>fields[key]);if(!entries.length)return res.status(400).json({error:'No supported fields'});if(req.body.status!==undefined&&!['registration','in_progress','completed','cancelled'].includes(req.body.status))return res.status(400).json({error:'Invalid tournament status'});for(const key of ['maxParticipants','entryFeePoints','prizePoolPoints','prize1st','prize2nd','prize3rd'])if(req.body[key]!==undefined&&(!Number.isInteger(Number(req.body[key]))||Number(req.body[key])<0))return res.status(400).json({error:`${key} must be a non-negative integer`});try{const tournament=await transaction(async db=>{const before=(await db.query('SELECT * FROM tournaments WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!before)throw new Error('Tournament not found');const values=entries.map(([,value])=>value===''?null:value),set=entries.map(([key],index)=>`${fields[key]}=$${index+1}`).join(',');const r=await db.query(`UPDATE tournaments SET ${set},updated_at=NOW() WHERE id=$${values.length+1} RETURNING *`,[...values,req.params.id]);await audit(db,req,'tournament.update','tournament',req.params.id,{before,after:r.rows[0]});return r.rows[0]});res.json({tournament})}catch(e:any){res.status(400).json({error:e.message})}})
  router.post('/tournaments/:id/participants',async(req:AdminRequest,res)=>{try{const {userId}=req.body;if(!userId)return res.status(400).json({error:'userId is required'});const participant=await transaction(async db=>{const tournament=(await db.query('SELECT max_participants,current_participants FROM tournaments WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!tournament)throw new Error('Tournament not found');if(tournament.max_participants&&tournament.current_participants>=tournament.max_participants)throw new Error('Tournament is full');const user=(await db.query('SELECT id FROM users WHERE id=$1 AND deleted_at IS NULL',[userId])).rows[0];if(!user)throw new Error('User not found');const r=await db.query('INSERT INTO tournament_participants(tournament_id,user_id) VALUES($1,$2) RETURNING *',[req.params.id,userId]);await db.query('UPDATE tournaments SET current_participants=current_participants+1,updated_at=NOW() WHERE id=$1',[req.params.id]);await audit(db,req,'tournament.participant.add','tournament',req.params.id,{userId});return r.rows[0]});res.status(201).json({participant})}catch(e:any){res.status(e.code==='23505'?409:400).json({error:e.code==='23505'?'User is already registered':e.message})}})
  router.delete('/tournaments/:id/participants/:userId',async(req:AdminRequest,res)=>{try{await transaction(async db=>{const r=await db.query('DELETE FROM tournament_participants WHERE tournament_id=$1 AND user_id=$2 RETURNING id',[req.params.id,req.params.userId]);if(!r.rows[0])throw new Error('Participant not found');await db.query('UPDATE tournaments SET current_participants=GREATEST(0,current_participants-1),updated_at=NOW() WHERE id=$1',[req.params.id]);await audit(db,req,'tournament.participant.remove','tournament',req.params.id,{userId:req.params.userId})});res.json({ok:true})}catch(e:any){res.status(400).json({error:e.message})}})
  router.delete('/tournaments/:id',async(req:AdminRequest,res)=>{try{await transaction(async db=>{const r=await db.query('DELETE FROM tournaments WHERE id=$1 RETURNING id',[req.params.id]);if(!r.rows[0])throw new Error('Tournament not found');await audit(db,req,'tournament.delete','tournament',req.params.id)});res.json({ok:true})}catch(e:any){res.status(400).json({error:e.message})}})
  router.get('/reports',async(_req,res)=>{try{res.json({items:(await pool.query(`SELECT r.*,reporter.username reporter_username,reported.username reported_username FROM reports r LEFT JOIN users reporter ON reporter.id=r.reporter_id LEFT JOIN users reported ON reported.id=r.reported_id ORDER BY r.created_at DESC LIMIT 200`)).rows})}catch(e:any){sendError(res,e)}})
  router.post('/reports/:id/action',async(req:AdminRequest,res)=>{const {action,notes,durationMinutes}=req.body;if(!notes||!String(notes).trim())return res.status(400).json({error:'Admin notes are required'});try{await transaction(async db=>{const r=await db.query('SELECT * FROM reports WHERE id=$1 FOR UPDATE',[req.params.id]);if(!r.rows[0])throw new Error('Report not found');if(action==='dismiss')await db.query("UPDATE reports SET status='dismissed',admin_notes=$1,reviewed_at=NOW() WHERE id=$2",[notes,req.params.id]);else if(['warning','resolve'].includes(action))await db.query("UPDATE reports SET status='actioned',admin_notes=$1,reviewed_at=NOW() WHERE id=$2",[notes,req.params.id]);else if(['mute','temporary_ban','permanent_ban'].includes(action)){if(action==='mute')await db.query("INSERT INTO user_mutes(user_id,reason,issued_by,expires_at) VALUES($1,$2,$3,NOW()+($4||' minutes')::interval)",[r.rows[0].reported_id,notes,req.adminId,durationMinutes||60]);else await db.query("INSERT INTO bans(user_id,reason,duration_minutes,expires_at,issued_by,ban_type) VALUES($1,$2,$3,CASE WHEN $3::int IS NULL THEN NULL ELSE NOW()+($3||' minutes')::interval END,$4,'platform')",[r.rows[0].reported_id,notes,action==='permanent_ban'?null:(durationMinutes||1440),req.adminId]);await db.query("UPDATE reports SET status='actioned',admin_notes=$1,reviewed_at=NOW() WHERE id=$2",[notes,req.params.id])}else throw new Error('Unsupported action');await audit(db,req,`report.${action}`,'report',req.params.id,{before:r.rows[0],notes,durationMinutes})});res.json({ok:true})}catch(e:any){res.status(400).json({error:e.message})}})
  router.get('/bans',async(_req,res)=>{try{res.json({items:(await pool.query('SELECT b.*,u.username,a.username issued_by_username FROM bans b JOIN users u ON u.id=b.user_id LEFT JOIN users a ON a.id=b.issued_by ORDER BY b.created_at DESC LIMIT 200')).rows})}catch(e:any){sendError(res,e)}})
  router.post('/bans',async(req:AdminRequest,res)=>{try{const {userId,reason,durationMinutes,permanent=false}=req.body;const ban=await transaction(async db=>{const r=await db.query("INSERT INTO bans(user_id,reason,duration_minutes,expires_at,issued_by,ban_type) VALUES($1,$2,$3,CASE WHEN $3::int IS NULL THEN NULL ELSE NOW()+($3||' minutes')::interval END,$4,'platform') RETURNING *",[userId,reason,permanent?null:durationMinutes,req.adminId]);await audit(db,req,'ban.create','user',userId,{reason,durationMinutes,permanent});return r.rows[0]});res.status(201).json({ban})}catch(e:any){res.status(400).json({error:e.message})}})
  router.patch('/bans/:id',async(req:AdminRequest,res)=>{const {reason,expiresAt,isActive}=req.body;if(reason===undefined&&expiresAt===undefined&&isActive===undefined)return res.status(400).json({error:'No supported fields'});if(reason!==undefined&&!String(reason).trim())return res.status(400).json({error:'Reason is required'});if(isActive!==undefined&&typeof isActive!=='boolean')return res.status(400).json({error:'isActive must be boolean'});try{const ban=await transaction(async db=>{const before=(await db.query('SELECT * FROM bans WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!before)throw new Error('Ban not found');const r=await db.query(`UPDATE bans SET reason=COALESCE($1,reason),expires_at=CASE WHEN $2::text IS NULL THEN expires_at WHEN $2='' THEN NULL ELSE $2::timestamptz END,is_active=COALESCE($3,is_active),lifted_at=CASE WHEN $3=false THEN NOW() WHEN $3=true THEN NULL ELSE lifted_at END WHERE id=$4 RETURNING *`,[reason===undefined?null:String(reason).trim(),expiresAt===undefined?null:expiresAt,isActive??null,req.params.id]);await audit(db,req,'ban.update','ban',req.params.id,{before,after:r.rows[0]});return r.rows[0]});res.json({ban})}catch(e:any){res.status(400).json({error:e.message})}})
  router.delete('/bans/:id',async(req:AdminRequest,res)=>{try{await transaction(async db=>{await db.query('UPDATE bans SET is_active=false,lifted_at=NOW() WHERE id=$1',[req.params.id]);await audit(db,req,'ban.lift','ban',req.params.id)});res.json({ok:true})}catch(e:any){res.status(400).json({error:e.message})}})
  router.get('/catalog',async(_req,res)=>{try{const [badges,frames]=await Promise.all([pool.query('SELECT * FROM badges ORDER BY name'),pool.query('SELECT * FROM frames ORDER BY name')]);res.json({badges:badges.rows,frames:frames.rows})}catch(e:any){sendError(res,e)}})
  router.post('/catalog/:type',async(req:AdminRequest,res)=>{if(!['badges','frames'].includes(req.params.type))return res.status(400).json({error:'Invalid catalog'});try{const {id,name,description='',rarity='COMMON',pricePoints=0,vipOnly=false,featured=false,isActive=true,metadata={}}=req.body;if(!id||!name)return res.status(400).json({error:'ID and name are required'});if(!['COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','VIP_EXCLUSIVE'].includes(rarity))return res.status(400).json({error:'Invalid rarity'});const item=await transaction(async db=>{const extra=req.params.type==='badges'?['icon','type',req.body.icon||null,req.body.itemType||'avatar']:['style',null,req.body.style||null,null];const sql=req.params.type==='badges'?`INSERT INTO badges(id,name,description,icon,type,rarity,price_points,vip_only,featured,is_active,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`:`INSERT INTO frames(id,name,description,style,rarity,price_points,vip_only,featured,is_active,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`;const values=req.params.type==='badges'?[id,name,description,extra[2],extra[3],rarity,Number(pricePoints),vipOnly,featured,isActive,metadata]:[id,name,description,extra[2],rarity,Number(pricePoints),vipOnly,featured,isActive,metadata];const r=await db.query(sql,values);await audit(db,req,'catalog.create',req.params.type,id,{item:r.rows[0]});return r.rows[0]});res.status(201).json({item})}catch(e:any){res.status(e.code==='23505'?409:400).json({error:e.code==='23505'?'Catalog ID already exists':e.message})}})
  router.patch('/catalog/:type/:id',async(req:AdminRequest,res)=>{if(!['badges','frames'].includes(req.params.type))return res.status(400).json({error:'Invalid catalog'});const common:Record<string,string>={name:'name',description:'description',rarity:'rarity',pricePoints:'price_points',vipOnly:'vip_only',featured:'featured',isActive:'is_active',metadata:'metadata'},specific:Record<string,string>=req.params.type==='badges'?{icon:'icon',itemType:'type'}:{style:'style'},fields:Record<string,string>={...common,...specific},entries=Object.entries(req.body).filter(([key])=>fields[key]);if(!entries.length)return res.status(400).json({error:'No supported fields'});try{const item=await transaction(async db=>{const before=(await db.query(`SELECT * FROM ${req.params.type} WHERE id=$1 FOR UPDATE`,[req.params.id])).rows[0];if(!before)throw new Error('Catalog item not found');const values=entries.map(([,v])=>v),set=entries.map(([key],i)=>`${fields[key]}=$${i+1}`).join(',');const r=await db.query(`UPDATE ${req.params.type} SET ${set} WHERE id=$${values.length+1} RETURNING *`,[...values,req.params.id]);await audit(db,req,'catalog.update',req.params.type,req.params.id,{before,after:r.rows[0]});return r.rows[0]});res.json({item})}catch(e:any){res.status(400).json({error:e.message})}})
  router.delete('/catalog/:type/:id',async(req:AdminRequest,res)=>{if(!['badges','frames'].includes(req.params.type))return res.status(400).json({error:'Invalid catalog'});try{await transaction(async db=>{const owned=req.params.type==='badges'?'owned_badges':'owned_frames',equipped=req.params.type==='badges'?'equipped_badge':'equipped_frame';const refs=await db.query(`SELECT COUNT(*)::int total FROM users WHERE $1=ANY(COALESCE(${owned},'{}'::text[])) OR ${equipped}=$1`,[req.params.id]);if(refs.rows[0].total>0)throw new Error('Catalog item is owned or equipped; disable it instead');const r=await db.query(`DELETE FROM ${req.params.type} WHERE id=$1 RETURNING id`,[req.params.id]);if(!r.rows[0])throw new Error('Catalog item not found');await audit(db,req,'catalog.delete',req.params.type,req.params.id)});res.json({ok:true})}catch(e:any){res.status(400).json({error:e.message})}})
  router.get('/logs',async(req,res)=>{const page=int(req.query.page,1),limit=int(req.query.limit,50),q=String(req.query.q||'').trim(),action=String(req.query.action||'').trim(),targetType=String(req.query.targetType||'').trim(),dateFrom=String(req.query.dateFrom||'').trim(),dateTo=String(req.query.dateTo||'').trim();try{const where=`($1='' OR u.username ILIKE '%'||$1||'%' OR l.action ILIKE '%'||$1||'%' OR l.target_id ILIKE '%'||$1||'%') AND ($2='' OR l.action=$2) AND ($3='' OR l.target_type=$3) AND ($4='' OR l.created_at >= $4::timestamptz) AND ($5='' OR l.created_at <= $5::timestamptz)`,params=[q,action,targetType,dateFrom,dateTo];const [rows,count]=await Promise.all([pool.query(`SELECT l.*,u.username admin_username FROM admin_audit_logs l LEFT JOIN users u ON u.id=l.admin_id WHERE ${where} ORDER BY l.created_at DESC LIMIT $6 OFFSET $7`,[...params,limit,(page-1)*limit]),pool.query(`SELECT COUNT(*)::int total FROM admin_audit_logs l LEFT JOIN users u ON u.id=l.admin_id WHERE ${where}`,params)]);res.json({items:rows.rows,total:count.rows[0].total,page,limit})}catch(e:any){sendError(res,e)}})
  router.get('/system',async(_req,res)=>{const started=Date.now();try{const db=await pool.query('SELECT NOW() now');const latencyMs=Date.now()-started;const [settings,cache,admins]=await Promise.all([pool.query('SELECT * FROM platform_settings ORDER BY key'),pool.query('SELECT COUNT(*)::int cached_users FROM users WHERE last_steam_check>NOW()-INTERVAL \'24 hours\''),pool.query(`SELECT id,username,last_seen FROM users WHERE role='admin' AND ${onlineUserPredicate('users')} ORDER BY last_seen DESC`)]);const isRailway=Boolean(process.env.RAILWAY_ENVIRONMENT_NAME||process.env.RAILWAY_PROJECT_ID);res.json({database:{ok:true,latencyMs,time:db.rows[0].now},api:{ok:true},steamApi:{configured:Boolean(process.env.STEAM_API_KEY)},environment:{provider:isRailway?'railway':'local'},cache:cache.rows[0],settings:settings.rows,onlineAdmins:admins.rows})}catch(e:any){sendError(res,e,503)}})
  router.put('/system/settings/:key',async(req:AdminRequest,res)=>{try{await transaction(async db=>{await db.query('INSERT INTO platform_settings(key,value,updated_by,updated_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_by=EXCLUDED.updated_by,updated_at=NOW()',[req.params.key,JSON.stringify(req.body.value),req.adminId]);await audit(db,req,'settings.update','setting',req.params.key,{value:req.body.value})});res.json({ok:true})}catch(e:any){res.status(400).json({error:e.message})}})
  router.post('/system/cache/clear',async(req:AdminRequest,res)=>{try{const cleared=await transaction(async db=>{const r=await db.query('UPDATE users SET last_steam_check=NULL WHERE last_steam_check IS NOT NULL');await audit(db,req,'cache.clear','system',undefined,{cache:'steam_profile',rows:r.rowCount});return r.rowCount||0});res.json({cleared})}catch(e:any){res.status(400).json({error:e.message})}})
  return router
}
