import { useEffect,useState } from 'react'
import { Activity,AlertTriangle } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '../ui/button'
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from '../ui/dialog'
import { Input } from '../ui/input'
import { adminAPI } from '../../utils/adminApi'
import type { AdminRow } from './adminTypes'
import type { AdminBanAction,AdminReportAction } from './AdminTable'
import { displayPlayerName } from '../../utils/displayName'

type Props={kind:'report'|'ban'|null;row:AdminRow|null;action:AdminReportAction|AdminBanAction|null;users?:AdminRow[];onClose:()=>void;onReportSaved:(report:AdminRow)=>void;onBanSaved:(ban:AdminRow|null,id?:string)=>void}
const fieldClass='mt-1 border-orange-900/30 bg-black/30'
const playerName=(player:any)=>displayPlayerName({display_name:player?.display_name,displayName:player?.displayName,username:player?.username},'Player')

export function AdminModerationManagement({kind,row,action,users=[],onClose,onReportSaved,onBanSaved}:Props){
  const [detail,setDetail]=useState<any>(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('')
  useEffect(()=>{if(kind!=='report'||!row||!action)return;let live=true;setLoading(true);setError('');adminAPI.get(`/reports/${row.id}`).then(value=>live&&setDetail(value)).catch((e:any)=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false}},[kind,row?.id,action])
  if(!kind||!action)return null
  const report=detail?.report||row,title=kind==='report'?(action==='view'?'View report':action==='resolve'?'Resolve report':action==='dismiss'?'Dismiss report':action==='warn'?'Warn player':action==='ban'?'Ban player':action==='mute'?'Mute player':'Edit admin notes'):(action==='create'?'Add ban':action==='edit'?'Edit ban':'Remove ban')
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries());setSaving(true);setError('');try{
    if(kind==='report'){const result:any=await adminAPI.post(`/reports/${row?.id}/action`,{action,notes:data.notes,durationMinutes:['ban','mute'].includes(action)?Number(data.durationMinutes):undefined,permanent:action==='ban'&&data.permanent==='on'});if(!result?.report)throw new Error('Backend did not return the updated report');toast.success(`${title} completed`);onReportSaved(result.report)}
    else if(action==='create'){const result:any=await adminAPI.post('/bans',{userId:data.userId,reason:data.reason,permanent:data.permanent==='on',durationMinutes:data.permanent==='on'?null:Number(data.durationMinutes),adminReason:data.adminReason});if(!result?.ban)throw new Error('Backend did not return the new ban');toast.success('Ban added');onBanSaved(result.ban)}
    else if(action==='edit'){const result:any=await adminAPI.patch(`/bans/${row?.id}`,{reason:data.reason,permanent:data.permanent==='on',durationMinutes:data.permanent==='on'?null:Number(data.durationMinutes),adminReason:data.adminReason});if(!result?.ban)throw new Error('Backend did not return the updated ban');toast.success('Ban updated');onBanSaved(result.ban)}
    else{const result:any=await adminAPI.delete(`/bans/${row?.id}`,{reason:data.adminReason});if(!result?.removed)throw new Error('Backend did not confirm ban removal');toast.success('Ban removed');onBanSaved(result.ban)}
    onClose()
  }catch(e:any){setError(e.message||'Moderation action failed')}finally{setSaving(false)}}
  const field=(name:string,label:string,value:any='',type='text',required=true)=><label className="text-xs text-slate-400">{label}<Input name={name} type={type} defaultValue={value??''} required={required} className={fieldClass}/></label>
  if(kind==='report'&&action==='view')return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="max-h-[calc(100vh-2rem)] overflow-y-auto border-orange-900/30 bg-[#111113]"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>Complete PostgreSQL report record and moderation history.</DialogDescription></DialogHeader>{loading?<div className="flex items-center gap-2 py-10 text-sm text-slate-400"><Activity className="animate-spin"/>Loading report…</div>:error?<div className="rounded border border-red-500/30 p-3 text-sm text-red-300">{error}</div>:<div className="space-y-4 text-xs"><dl className="grid gap-2 sm:grid-cols-[140px_1fr]">{Object.entries(report||{}).map(([key,value])=><div className="contents" key={key}><dt className="text-slate-500">{key.replaceAll('_',' ')}</dt><dd className="break-words text-slate-200">{value==null?'—':String(value)}</dd></div>)}</dl><section className="rounded border border-orange-900/20 p-3"><h3 className="mb-2 uppercase text-orange-400">Active restrictions</h3><p>Bans: {detail?.activeBans?.length??0} · Mutes: {detail?.activeMutes?.length??0}</p></section><section className="rounded border border-orange-900/20 p-3"><h3 className="mb-2 uppercase text-orange-400">Audit history</h3>{detail?.auditHistory?.length?detail.auditHistory.map((item:any)=><p key={item.id||item.created_at} className="border-t border-orange-900/10 py-2">{new Date(item.created_at).toLocaleString()} · {item.action}</p>):<p className="text-slate-500">No actions recorded.</p>}</section></div>}<DialogFooter><Button variant="outline" onClick={onClose}>Close</Button></DialogFooter></DialogContent></Dialog>
  const isReport=kind==='report',isBanForm=kind==='ban'&&['create','edit'].includes(action),defaultPermanent=kind==='ban'&&action==='edit'&&!row?.expires_at
  return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="max-h-[calc(100vh-2rem)] overflow-y-auto border-orange-900/30 bg-[#111113]"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{isReport?`${report?.reported_username||'Reported player'} · ${report?.status}`:'Ban changes take effect immediately.'}</DialogDescription></DialogHeader>{loading?<div className="flex items-center gap-2 py-10 text-sm text-slate-400"><Activity className="animate-spin"/>Loading current data…</div>:<form onSubmit={submit} className="space-y-4">
    {isReport&&<><p className="rounded border border-orange-900/20 p-3 text-xs text-slate-400">{report?.reason}: {report?.description||'No description supplied.'}</p>{['ban','mute'].includes(action)&&field('durationMinutes',action==='ban'?'Temporary duration in minutes (check permanent below)':'Mute duration in minutes',action==='mute'?60:1440,'number')}{action==='ban'&&<label className="flex items-center gap-2 text-xs text-slate-400"><input name="permanent" type="checkbox"/>Permanent ban</label>}<label className="text-xs text-slate-400">Admin notes<textarea name="notes" defaultValue={action==='notes'?report?.admin_notes||'':''} required className={`${fieldClass} min-h-28 w-full rounded border p-3`}/></label></>}
    {kind==='ban'&&action==='create'&&<label className="text-xs text-slate-400">Player<select name="userId" required defaultValue="" className={`${fieldClass} h-10 w-full rounded border px-3`}><option value="" disabled>Select an active player</option>{users.map(user=><option key={user.id} value={user.id}>{playerName(user)} ({user.username})</option>)}</select></label>}
    {isBanForm&&<>{field('reason','Ban reason',row?.reason||'')}<label className="flex items-center gap-2 text-xs text-slate-400"><input name="permanent" type="checkbox" defaultChecked={defaultPermanent}/>Permanent ban</label>{field('durationMinutes','Temporary duration in minutes',row?.duration_minutes||1440,'number')}{field('adminReason','Required administrative reason','')}</>}
    {kind==='ban'&&action==='remove'&&<><p className="rounded border border-red-500/30 bg-red-950/10 p-3 text-sm text-red-300">Removing this ban restores access immediately. The moderation record remains in history.</p>{field('adminReason','Required removal reason','')}</>}
    {error&&<div className="flex gap-2 rounded border border-red-500/30 bg-red-950/10 p-3 text-xs text-red-300"><AlertTriangle size={15}/>{error}</div>}<DialogFooter><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={saving} variant={action==='remove'||action==='ban'?'destructive':'default'}>{saving?'Saving…':'Confirm action'}</Button></DialogFooter>
  </form>}</DialogContent></Dialog>
}
