import { useEffect, useState } from 'react'
import { Activity, AlertTriangle } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '../ui/button'
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from '../ui/dialog'
import { Input } from '../ui/input'
import { adminAPI } from '../../utils/adminApi'
import type { AdminRow } from './adminTypes'
import type { AdminUserAction } from './AdminTable'
import { displayPlayerName } from '../../utils/displayName'

type Props={row:AdminRow|null;action:Exclude<AdminUserAction,'view'>|null;currentUserId?:string;onClose:()=>void;onSaved:(user:AdminRow)=>void;onDeleted:(id:string)=>void}
const titles={edit:'Edit user',points:'Manage points',vip:'Manage VIP',role:'Manage role',badges:'Manage badges',frames:'Manage frames',ban:'Ban / unban user',deactivate:'Deactivate / restore user',permanent:'Permanently delete user'} as const
const fieldClass='mt-1 border-orange-900/30 bg-black/30'

export function AdminUserManagement({row,action,currentUserId,onClose,onSaved,onDeleted}:Props){
  const [detail,setDetail]=useState<any>(null),[catalog,setCatalog]=useState<any>(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('')
  useEffect(()=>{if(!row||!action)return;let live=true;setLoading(true);setError('');Promise.all([adminAPI.get(`/users/${row.id}`),['badges','frames'].includes(action)?adminAPI.get('/catalog'):Promise.resolve(null)]).then(([d,c])=>{if(live){setDetail(d);setCatalog(c)}}).catch((e:any)=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false}},[row?.id,action])
  if(!row||!action)return null
  const user=detail?.user||row
  const canonicalName=displayPlayerName({display_name:user.display_name,displayName:user.displayName,username:user.username},'Player')
  const localDisplayName=user.local_display_name ?? user.display_name
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget),data=Object.fromEntries(f.entries());setSaving(true);setError('');try{let result:any
    if(action==='edit')result=await adminAPI.patch(`/users/${row.id}`,{username:data.username,displayName:data.displayName,email:data.email,points:Number(data.points),experience:Number(data.experience),level:Number(data.level),wins:Number(data.wins),losses:Number(data.losses),profileVisibility:data.profileVisibility,showOnlineStatus:data.showOnlineStatus==='on',reason:data.reason})
    if(action==='points')result=await adminAPI.post(`/users/${row.id}/action`,{action:data.operation,amount:Number(data.amount),reason:data.reason})
    if(action==='vip')result=await adminAPI.post(`/users/${row.id}/action`,data.operation==='remove'?{action:'remove_vip',reason:data.reason}:{action:'grant_vip',expiresAt:data.permanent==='on'?null:data.expiresAt||null,vipMethod:data.vipMethod,reason:data.reason})
    if(action==='role')result=await adminAPI.patch(`/users/${row.id}`,{role:data.role,reason:data.reason})
    if(action==='badges'||action==='frames')result=await adminAPI.post(`/users/${row.id}/action`,{action:data.operation,itemId:data.itemId||undefined,reason:data.reason})
    if(action==='ban')result=await adminAPI.post(`/users/${row.id}/action`,user.activeBan?{action:'unban',reason:data.reason}:{action:'ban',reason:data.reason,expiresAt:data.permanent==='on'?null:data.expiresAt||null})
    if(action==='deactivate')result=await adminAPI.post(`/users/${row.id}/${user.deleted_at?'restore':'deactivate'}`,{reason:data.reason,confirmSelf:data.confirmSelf==='on',confirmSelfAgain:data.confirmSelfAgain==='on'})
    if(action==='permanent'){const response:any=await adminAPI.delete(`/users/${row.id}/permanent`,{reason:data.reason,confirmation:data.confirmation,confirmSelf:data.confirmSelf==='on',confirmSelfAgain:data.confirmSelfAgain==='on'});if(!response?.success)throw new Error('Backend did not confirm permanent deletion');toast.success('User permanently deleted');onDeleted(row.id);onClose();return}
    const saved=result?.user;if(!saved)throw new Error('Backend did not return the updated user');toast.success(`${titles[action]} completed`);onSaved(saved);onClose()
  }catch(e:any){setError(e.message||'Administrative action failed')}finally{setSaving(false)}}
  const label=(name:string,text:string,type='text',value:any='',required=true)=><label className="text-xs text-slate-400">{text}<Input className={fieldClass} name={name} type={type} defaultValue={value??''} required={required}/></label>
  const reason=<>{label('reason','Required administrative reason','text','',true)}</>
  const confirm=<label className="flex items-start gap-2 text-xs text-slate-400"><input name="confirmed" type="checkbox" required className="mt-0.5"/>I confirm this sensitive administrative action.</label>
  const items=(action==='badges'?catalog?.badges:catalog?.frames)||[]
  return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="max-h-[calc(100vh-2rem)] overflow-y-auto border-orange-900/30 bg-[#111113]"><DialogHeader><DialogTitle>{titles[action]}</DialogTitle><DialogDescription>{canonicalName} · changes are validated, persisted, and audited.</DialogDescription></DialogHeader>{loading?<div className="flex items-center gap-2 py-10 text-sm text-slate-400"><Activity className="animate-spin"/>Loading current PostgreSQL data…</div>:<form className="space-y-4" onSubmit={submit}>
    {action==='edit'&&<><div className="grid gap-3 sm:grid-cols-2">{label('username','Username','text',user.username)}{label('displayName','Display name','text',localDisplayName,false)}{label('email','Email','email',user.email)}{label('points','Points','number',user.points)}{label('experience','XP','number',user.experience)}{label('level','Level','number',user.level)}{label('wins','Wins','number',user.wins)}{label('losses','Losses','number',user.losses)}<label className="text-xs text-slate-400">Profile visibility<select name="profileVisibility" defaultValue={user.profile_visibility||'public'} className={`${fieldClass} h-10 w-full rounded border px-3`}><option value="public">Public</option><option value="friends">Friends</option><option value="private">Private</option></select></label><label className="flex items-center gap-2 self-end pb-3 text-xs text-slate-400"><input name="showOnlineStatus" type="checkbox" defaultChecked={user.show_online_status!==false}/>Show online status</label></div>{reason}</>}
    {action==='points'&&<><label className="text-xs text-slate-400">Operation<select name="operation" className={`${fieldClass} h-10 w-full rounded border px-3`}><option value="give_points">Add</option><option value="remove_points">Remove</option><option value="set_points">Set exact balance</option></select></label>{label('amount',`Amount (current: ${user.points})`,'number',0)}{reason}{confirm}</>}
    {action==='vip'&&<><p className="rounded border border-orange-900/20 p-3 text-xs text-slate-400">Current: {user.is_premium?'Active':'Inactive'} · expires {user.vip_expires_at?new Date(user.vip_expires_at).toLocaleString():'never'} · method {user.vip_method||'none'}</p><label className="text-xs text-slate-400">Operation<select name="operation" className={`${fieldClass} h-10 w-full rounded border px-3`}><option value="grant">Grant / update</option><option value="remove">Remove</option></select></label><label className="text-xs text-slate-400">Method<select name="vipMethod" defaultValue={user.vip_method||'points'} className={`${fieldClass} h-10 w-full rounded border px-3`}><option value="points">Points</option><option value="payment">Payment</option></select></label>{label('expiresAt','Expiration','datetime-local',user.vip_expires_at?new Date(user.vip_expires_at).toISOString().slice(0,16):'',false)}<label className="flex gap-2 text-xs text-slate-400"><input name="permanent" type="checkbox"/>No expiration</label>{reason}{confirm}</>}
    {action==='role'&&<><label className="text-xs text-slate-400">Role<select name="role" defaultValue={user.role} className={`${fieldClass} h-10 w-full rounded border px-3`}><option value="user">User</option><option value="admin">Administrator</option></select></label>{reason}{confirm}</>}
    {(action==='badges'||action==='frames')&&<><p className="text-xs text-slate-400">Owned: {(action==='badges'?user.owned_badges:user.owned_frames)?.join(', ')||'None'} · Equipped: {action==='badges'?user.equipped_badge:user.equipped_frame||'None'}</p><label className="text-xs text-slate-400">Operation<select name="operation" className={`${fieldClass} h-10 w-full rounded border px-3`}><option value={`grant_${action.slice(0,-1)}`}>Grant</option><option value={`remove_${action.slice(0,-1)}`}>Remove</option><option value={`equip_${action.slice(0,-1)}`}>Equip</option><option value={`unequip_${action.slice(0,-1)}`}>Unequip</option></select></label><label className="text-xs text-slate-400">Catalog item<select name="itemId" className={`${fieldClass} h-10 w-full rounded border px-3`}><option value="">None (for unequip)</option>{items.map((item:any)=><option key={item.id} value={item.id}>{item.name} ({item.id})</option>)}</select></label>{reason}</>}
    {action==='ban'&&<>{user.activeBan?<p className="rounded border border-red-500/30 p-3 text-xs text-red-300">Active ban: {user.activeBan.reason} · {user.activeBan.expires_at?new Date(user.activeBan.expires_at).toLocaleString():'Permanent'}</p>:<>{label('expiresAt','Expiration','datetime-local','',false)}<label className="flex gap-2 text-xs text-slate-400"><input name="permanent" type="checkbox"/>Permanent ban</label></>}{reason}{confirm}</>}
    {action==='deactivate'&&<><p className="text-sm text-slate-300">{user.deleted_at?'Restore this account and allow normal access again?':'Soft-deactivate this account? Its database record will be preserved.'}</p>{reason}{confirm}{!user.deleted_at&&user.id===currentUserId&&<label className="flex items-start gap-2 text-xs text-red-300"><input name="confirmSelfAgain" type="checkbox" required className="mt-0.5"/>Second confirmation: I understand I am deactivating my own administrator account.</label>}{!user.deleted_at&&user.id===currentUserId&&<input type="hidden" name="confirmSelf" value="on"/>}</>}
    {action==='permanent'&&<><div className="rounded border border-red-500/40 bg-red-950/20 p-3 text-sm text-red-300">This permanently removes the account and disposable related data. This cannot be undone.</div>{label('confirmation',`Type ${user.username} or DELETE to confirm`,'text','',true)}{reason}<label className="flex items-start gap-2 text-xs text-red-300"><input name="confirmSelf" type="checkbox" required className="mt-0.5"/>I understand this permanently deletes the user from PostgreSQL.</label>{user.id===currentUserId&&<label className="flex items-start gap-2 text-xs text-red-300"><input name="confirmSelfAgain" type="checkbox" required className="mt-0.5"/>Second confirmation: I understand I am permanently deleting my own administrator account.</label>}</>}
    {error&&<div className="flex gap-2 rounded border border-red-500/30 bg-red-950/10 p-3 text-xs text-red-300"><AlertTriangle size={15}/>{error}</div>}<DialogFooter><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={saving}>{saving?'Saving…':'Confirm and save'}</Button></DialogFooter></form>}</DialogContent></Dialog>
}
