import { Activity, Database, HardDrive, Server, TrainFront, Wrench } from 'lucide-react'
import { Button } from '../ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card'
import { Switch } from '../ui/switch'
import { AdminStatusBadge } from './AdminStatusBadge'

export function AdminSystem({data,onRefresh,onSetting}:{data:any;onRefresh:()=>void;onSetting:(key:string,value:any)=>void}) {
  const settings=data.settings as any[]
  const provider=data.environment.provider
  return <div className="grid min-w-0 gap-6 xl:grid-cols-2"><div className="space-y-6"><Panel title="Service Health" description="Facts returned by the live backend"><Health label="PostgreSQL" detail={`${data.database.latencyMs} ms SELECT NOW() response`} state={data.database.ok?'online':'offline'} icon={Database}/><Health label="API Server" detail="Authenticated administration health request succeeded" state={data.api.ok?'online':'offline'} icon={Server}/><Health label="Steam API" detail={data.steamApi.configured?'Configured on the server':'Not configured locally'} state={data.steamApi.configured?'configured':'not configured'} icon={Activity}/><Health label="Railway Environment" detail={provider==='railway'?'Railway production environment detected':'Local environment'} state={provider} icon={TrainFront}/></Panel><Panel title="Cache & Storage" description="Database-backed operational records"><Health label="Steam Cache" detail={`${data.cache.cached_users} fresh records in the last 24 hours`} state={data.cache.cached_users===0?'empty':'available'} icon={HardDrive}/><Health label="Database Storage" detail="Persistent storage is available because PostgreSQL responded" state={data.database.ok?'online':'offline'} icon={Database}/></Panel></div>
    <div className="space-y-6"><Panel title="Platform Settings" description="Runtime controls stored in platform_settings"><Button size="sm" variant="outline" className="mb-3" onClick={()=>{const key=window.prompt('Setting key'),raw=window.prompt('JSON value','false');if(key&&raw!==null){try{onSetting(key,JSON.parse(raw))}catch{window.alert('Value must be valid JSON')}}}}>Add setting</Button>{settings.length?settings.map(setting=><div key={setting.key} className="flex min-h-16 items-center justify-between gap-5 border-b border-orange-900/15 py-3 last:border-0"><div className="min-w-0"><p className="text-sm text-slate-200">{setting.key.split('_').join(' ')}</p><p className="mt-1 text-xs text-slate-600">{setting.description||'No description stored'}</p></div>{typeof setting.value==='boolean'?<Switch checked={setting.value} onCheckedChange={value=>onSetting(setting.key,value)}/>:<Button variant="ghost" onClick={()=>{const raw=window.prompt('JSON value',JSON.stringify(setting.value));if(raw!==null){try{onSetting(setting.key,JSON.parse(raw))}catch{window.alert('Value must be valid JSON')}}}} className="max-w-48 truncate rounded bg-black/30 px-3 py-1.5 text-xs text-slate-400">{JSON.stringify(setting.value)}</Button>}</div>):<p className="py-8 text-center text-sm text-slate-600">No settings configured.</p>}</Panel><Panel title="Environment Summary" description="Non-secret deployment information"><dl className="grid grid-cols-2 gap-4 text-xs"><Summary label="Runtime" value={provider==='railway'?'Railway':'Local'}/><Summary label="Database" value={data.database.ok?'Connected':'Unavailable'}/><Summary label="Steam API" value={data.steamApi.configured?'Configured':'Not configured locally'}/><Summary label="Cache records" value={String(data.cache.cached_users)}/></dl></Panel><Panel title="Quick Diagnostics" description="Safe, read-only operational checks"><Button variant="outline" onClick={onRefresh} className="h-10 justify-start gap-2 border-orange-900/30"><Wrench size={15}/>Refresh health</Button></Panel></div></div>
}

function Panel({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <Card className="min-w-0 border-orange-900/25 bg-[#101011]"><CardHeader className="border-b border-orange-900/15"><CardTitle className="text-base text-slate-100">{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="p-5">{children}</CardContent></Card>}
function Health({label,detail,state,icon:Icon}:{label:string;detail:string;state:string;icon:any}){return <div className="flex min-h-16 items-center gap-4 border-b border-orange-900/15 py-3 last:border-0"><div className="grid size-9 shrink-0 place-items-center rounded-md bg-orange-500/10 text-orange-400"><Icon size={17}/></div><div className="min-w-0 flex-1"><p className="text-sm text-slate-200">{label}</p><p className="truncate text-xs text-slate-600">{detail}</p></div><AdminStatusBadge value={state}/></div>}
function Summary({label,value}:{label:string;value:string}){return <div className="rounded-md border border-orange-900/20 bg-black/20 p-3"><dt className="text-slate-600">{label}</dt><dd className="mt-1 truncate text-slate-300">{value}</dd></div>}
