import { useEffect,useState } from 'react'
import { Activity,AlertTriangle,CheckCircle,Database,HardDrive,Server,TrainFront,Wrench } from 'lucide-react'
import { Button } from '../ui/button'
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from '../ui/card'
import { Input } from '../ui/input'
import { Switch } from '../ui/switch'
import { AdminStatusBadge } from './AdminStatusBadge'

const defaults:any={maintenance_mode:false,registration_enabled:true,platform_announcement:{enabled:false,title:'',message:''},matchmaking_defaults:{gameMode:'classic-deathmatch',selectedMaps:['dm_crossfire'],queueTimeoutMinutes:15},xp_defaults:{win:50,loss:10},points_defaults:{startingBalance:1000,win:0,loss:0}}
const settingsFromRows=(rows:any[])=>{const stored=Object.fromEntries((rows||[]).map((setting:any)=>[setting.key,setting.value]));return{...defaults,...stored,platform_announcement:{...defaults.platform_announcement,...stored.platform_announcement},matchmaking_defaults:{...defaults.matchmaking_defaults,...stored.matchmaking_defaults},xp_defaults:{...defaults.xp_defaults,...stored.xp_defaults},points_defaults:{...defaults.points_defaults,...stored.points_defaults}}}

export function AdminSystem({data,onRefresh,onSave,onToggleGame}:{data:any;onRefresh:()=>void;onSave:(settings:Record<string,any>)=>Promise<any[]>;onToggleGame:(gameId:string,enabled:boolean)=>Promise<void>}) {
  const provider=data.environment.provider,[draft,setDraft]=useState<any>(defaults),[status,setStatus]=useState<'idle'|'unsaved'|'saving'|'saved'|'error'>('idle'),[error,setError]=useState('')
  useEffect(()=>{setDraft(settingsFromRows(data.settings||[]));setStatus('idle');setError('')},[data.settings])
  const changed=()=>{setStatus('unsaved');setError('')}
  const set=(key:string,value:any)=>{changed();setDraft((current:any)=>({...current,[key]:value}))},nested=(key:string,field:string,value:any)=>{changed();setDraft((current:any)=>({...current,[key]:{...current[key],[field]:value}}))}
  const save=async()=>{setStatus('saving');setError('');try{const saved=await onSave(draft);setDraft(settingsFromRows(saved));setStatus('saved')}catch(e:any){setError(e.message||'Unable to save platform settings');setStatus('error')}}
  const number=(group:string,key:string,label:string)=><label className="text-xs text-slate-400">{label}<Input type="number" min={0} value={draft[group]?.[key]??0} onChange={event=>nested(group,key,Number(event.target.value))} className="mt-1 border-orange-900/30 bg-black/30"/></label>
  return <div className="grid min-w-0 gap-6 xl:grid-cols-2"><div className="space-y-6"><Panel title="Service Health" description="Facts returned by the live backend"><Health label="PostgreSQL" detail={`${data.database.latencyMs} ms SELECT NOW() response`} state={data.database.ok?'online':'offline'} icon={Database}/><Health label="API Server" detail="Authenticated administration health request succeeded" state={data.api.ok?'online':'offline'} icon={Server}/><Health label="Steam API" detail={data.steamApi.configured?'Configured on the server':'Not configured locally'} state={data.steamApi.configured?'configured':'not configured'} icon={Activity}/><Health label="Railway Environment" detail={provider==='railway'?'Railway production environment detected':'Local environment'} state={provider} icon={TrainFront}/></Panel><Panel title="Cache & Storage" description="Database-backed operational records"><Health label="Steam Cache" detail={`${data.cache.cached_users} fresh records in the last 24 hours`} state={data.cache.cached_users===0?'empty':'available'} icon={HardDrive}/><Health label="Database Storage" detail="Persistent storage is available because PostgreSQL responded" state={data.database.ok?'online':'offline'} icon={Database}/></Panel></div>
    <div className="space-y-6"><Panel title="Available games" description="Only enabled games are exposed to the platform frontend"><div className="space-y-4">{(data.games||[]).map((game:any)=><SettingToggle key={game.game_id} label={({hl1:'Half-Life 1',cs16:'Counter-Strike 1.6',l4d2:'Left 4 Dead 2',cod4:'Call of Duty 4 Promod'} as Record<string,string>)[game.game_id]||game.game_id} detail={game.enabled?'Available on the platform':'Backend data retained; hidden from the frontend'} checked={game.enabled} onChange={enabled=>void onToggleGame(game.game_id,enabled)}/>)}</div></Panel><Panel title="Platform Settings" description="Validated runtime defaults stored directly in PostgreSQL"><div className="space-y-5">
      <SettingToggle label="Maintenance mode" detail="Place the public platform into maintenance mode." checked={draft.maintenance_mode} onChange={value=>set('maintenance_mode',value)}/>
      <SettingToggle label="Registration enabled" detail="Allow creation of new user accounts." checked={draft.registration_enabled} onChange={value=>set('registration_enabled',value)}/>
      <section className="space-y-3 border-t border-orange-900/20 pt-4"><SettingToggle label="Platform announcement" detail="Publish the configured platform-wide announcement." checked={draft.platform_announcement?.enabled} onChange={value=>nested('platform_announcement','enabled',value)}/><Input value={draft.platform_announcement?.title||''} onChange={event=>nested('platform_announcement','title',event.target.value)} placeholder="Announcement title" className="border-orange-900/30 bg-black/30"/><textarea value={draft.platform_announcement?.message||''} onChange={event=>nested('platform_announcement','message',event.target.value)} placeholder="Announcement message" className="min-h-24 w-full rounded border border-orange-900/30 bg-black/30 p-3 text-sm"/></section>
      <section className="space-y-3 border-t border-orange-900/20 pt-4"><h3 className="text-sm text-orange-300">Default matchmaking values</h3><label className="text-xs text-slate-400">Game mode<select value={draft.matchmaking_defaults?.gameMode} onChange={event=>nested('matchmaking_defaults','gameMode',event.target.value)} className="mt-1 h-10 w-full rounded border border-orange-900/30 bg-black/30 px-3"><option value="classic-deathmatch">Classic deathmatch</option><option value="instagib-mode">Instagib mode</option></select></label><label className="text-xs text-slate-400">Selected maps (comma-separated)<Input value={(draft.matchmaking_defaults?.selectedMaps||[]).join(', ')} onChange={event=>nested('matchmaking_defaults','selectedMaps',event.target.value.split(',').map(value=>value.trim()).filter(Boolean))} className="mt-1 border-orange-900/30 bg-black/30"/></label>{number('matchmaking_defaults','queueTimeoutMinutes','Queue timeout in minutes')}</section>
      <section className="border-t border-orange-900/20 pt-4"><h3 className="mb-3 text-sm text-orange-300">Default XP values</h3><div className="grid gap-3 sm:grid-cols-2">{number('xp_defaults','win','Winner XP')}{number('xp_defaults','loss','Participant XP')}</div></section>
      <section className="border-t border-orange-900/20 pt-4"><h3 className="mb-3 text-sm text-orange-300">Default points values</h3><div className="grid gap-3 sm:grid-cols-3">{number('points_defaults','startingBalance','Starting balance')}{number('points_defaults','win','Winner points')}{number('points_defaults','loss','Participant points')}</div></section>
      {status==='unsaved'&&<div className="rounded border border-amber-500/30 bg-amber-950/20 p-3 text-xs text-amber-200">Unsaved changes</div>}
      {status==='saved'&&<div className="flex gap-2 rounded border border-green-500/30 bg-green-950/20 p-3 text-xs text-green-300"><CheckCircle size={15}/>Settings saved</div>}
      {error&&<div className="flex gap-2 rounded border border-red-500/30 bg-red-950/10 p-3 text-xs text-red-300"><AlertTriangle size={15}/>{error}</div>}<Button onClick={save} disabled={status==='saving'||status==='idle'||status==='saved'} className="w-full">{status==='saving'?'Saving…':'Save platform settings'}</Button>
    </div></Panel><Panel title="Quick Diagnostics" description="Safe, read-only operational checks"><Button variant="outline" onClick={onRefresh} className="h-10 justify-start gap-2 border-orange-900/30"><Wrench size={15}/>Refresh health</Button></Panel></div></div>
}

function SettingToggle({label,detail,checked,onChange}:{label:string;detail:string;checked:boolean;onChange:(value:boolean)=>void}){return <div className="flex items-center justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm text-slate-200">{label}</p><span className={`rounded border px-2 py-0.5 text-[10px] font-semibold ${checked?'border-green-500/30 bg-green-950/30 text-green-300':'border-slate-700 bg-slate-900 text-slate-400'}`}>{checked?'ENABLED':'DISABLED'}</span></div><p className="mt-1 text-xs text-slate-600">{detail}</p></div><Switch checked={Boolean(checked)} onCheckedChange={onChange}/></div>}
function Panel({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <Card className="min-w-0 border-orange-900/25 bg-[#101011]"><CardHeader className="border-b border-orange-900/15"><CardTitle className="text-base text-slate-100">{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="p-5">{children}</CardContent></Card>}
function Health({label,detail,state,icon:Icon}:{label:string;detail:string;state:string;icon:any}){return <div className="flex min-h-16 items-center gap-4 border-b border-orange-900/15 py-3 last:border-0"><div className="grid size-9 shrink-0 place-items-center rounded-md bg-orange-500/10 text-orange-400"><Icon size={17}/></div><div className="min-w-0 flex-1"><p className="text-sm text-slate-200">{label}</p><p className="truncate text-xs text-slate-600">{detail}</p></div><AdminStatusBadge value={state}/></div>}
