import { Button } from '../ui/button'
import type { AdminRow,AdminSection } from './adminTypes'

type Mutate=(path:string,method:'post'|'patch'|'delete',body?:any)=>Promise<void>
type Confirm=(title:string,description:string,run:()=>Promise<void>)=>void

export function AdminExtendedActions({section,row,mutate,confirm}:{section:AdminSection;row:AdminRow;mutate:Mutate;confirm:Confirm}) {
  const promptPatch=(label:string,key:string,numeric=false)=>{const value=window.prompt(label,String(row[key.replace(/[A-Z]/g,m=>`_${m.toLowerCase()}`)]??''));if(value!==null)void mutate(`/users/${row.id}`,'patch',{[key]:numeric?Number(value):value,reason:'Admin details update'})}
  if(['users','vip'].includes(section))return <section className="grid gap-2 rounded-lg border border-orange-900/20 p-4 sm:grid-cols-2"><Button variant="outline" onClick={()=>promptPatch('Username','username')}>Edit username</Button>{['experience','level','wins','losses'].map(key=><Button key={key} variant="outline" onClick={()=>promptPatch(`Set ${key}`,key,true)}>Set {key}</Button>)}<Button variant="outline" onClick={()=>{const value=window.prompt('VIP method: points or payment',String(row.vip_method??''));if(value)void mutate(`/users/${row.id}`,'patch',{vipMethod:value})}}>Set VIP method</Button><Button variant="outline" onClick={()=>{const value=window.prompt('Exact VIP expiration (ISO timestamp, empty for none)',row.vip_expires_at?new Date(row.vip_expires_at).toISOString():'');if(value!==null)void mutate(`/users/${row.id}`,'patch',{vipExpiresAt:value||null,isPremium:true})}}>Set VIP expiration</Button><Button variant="outline" onClick={()=>void mutate(`/users/${row.id}/action`,'post',{action:'unmute',reason:'Administrative unmute'})}>Unmute</Button><Button variant="outline" onClick={()=>{const verified=window.confirm('Mark Steam verified?');const owns=window.confirm('Mark HL1 owned?');void mutate(`/users/${row.id}/action`,'post',{action:'steam_override',steamVerified:verified,ownsHL1:owns,reason:'Explicit admin Steam override'})}}>Steam override</Button>{row.deleted_at&&<Button onClick={()=>confirm('Restore user','Restore this soft-deleted account?',()=>mutate(`/users/${row.id}/action`,'post',{action:'restore',reason:'Administrative restore'}))}>Restore user</Button>}</section>
  if(section==='matchmaking')return <Button variant="destructive" onClick={()=>confirm('Remove queued player',`Remove ${row.username||row.user_id} from matchmaking?`,()=>mutate(`/queue/${row.user_id}`,'delete'))}>Remove from queue</Button>
  if(['badges','frames','store'].includes(section)){const type=section==='store'?String(row.catalog)==='frame'?'frames':'badges':section;return <section className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>{const name=window.prompt('Name',String(row.name??'')),price=window.prompt('Price points',String(row.price_points??0));if(name&&price!==null)void mutate(`/catalog/${type}/${row.id}`,'patch',{name,pricePoints:Number(price)})}}>Edit item</Button><Button variant="outline" onClick={()=>void mutate(`/catalog/${type}/${row.id}`,'patch',{featured:!row.featured})}>{row.featured?'Unfeature':'Feature'}</Button><Button variant="outline" onClick={()=>void mutate(`/catalog/${type}/${row.id}`,'patch',{isActive:!row.is_active})}>{row.is_active===false?'Enable':'Disable'}</Button><Button variant="destructive" onClick={()=>confirm('Delete catalog item','Deletion is blocked if any user owns or equips this item.',()=>mutate(`/catalog/${type}/${row.id}`,'delete'))}>Delete safely</Button></section>}
  return null
}
