import { useEffect, useMemo, useState } from 'react'
import { ArrowUpDown, ChevronLeft, ChevronRight, MoreHorizontal } from 'lucide-react'
import { Button } from '../ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '../ui/dropdown-menu'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../ui/table'
import { AdminStatusBadge } from './AdminStatusBadge'
import { formatAdminValue, sectionMeta, type AdminRow, type AdminSection } from './adminTypes'

export type AdminUserAction='view'|'edit'|'points'|'vip'|'role'|'badges'|'frames'|'ban'|'deactivate'|'permanent'
export type AdminServerAction='view'|'edit'|'status'|'assign'|'unassign'|'copy'|'delete'

type Column={key:string;label:string;render?:(row:AdminRow)=>React.ReactNode}
const status=(key:string)=>(row:AdminRow)=><AdminStatusBadge value={row[key]}/>
const columns:Partial<Record<AdminSection,Column[]>>={
  users:[{key:'username',label:'User',render:r=><div><p className="font-medium text-slate-200">{r.username}</p>{r.display_name&&r.display_name!==r.username&&<p className="text-[11px] text-slate-500">{r.display_name}</p>}</div>},{key:'is_online',label:'Presence',render:r=><AdminStatusBadge value={r.is_online?'online':'offline'}/>},{key:'email',label:'Email'},{key:'steam_verified',label:'Steam',render:r=><AdminStatusBadge value={r.steam_verified?'verified':r.steam_id?'linked':'unlinked'}/>},{key:'role',label:'Role',render:status('role')},{key:'level',label:'Level'},{key:'points',label:'Points'},{key:'is_premium',label:'VIP',render:r=><AdminStatusBadge value={r.is_premium?'active':'standard'}/>},{key:'last_seen',label:'Last seen'}],
  servers:[{key:'name',label:'Server'},{key:'game_id',label:'Game'},{key:'region',label:'Region'},{key:'public_host',label:'Public address',render:r=><span className="font-mono text-xs">{r.public_host}:{r.port}</span>},{key:'max_slots',label:'Slots'},{key:'status',label:'Status',render:status('status')}],
  matchmaking:[{key:'username',label:'Player'},{key:'game',label:'Game'},{key:'game_mode',label:'Mode'},{key:'selected_maps',label:'Maps'},{key:'waiting_seconds',label:'Waiting',render:r=><span>{r.waiting_seconds}s</span>},{key:'region',label:'Region'}],
  matches:[{key:'id',label:'Match ID',render:r=><span className="font-mono text-xs">{String(r.id).slice(0,8)}</span>},{key:'players',label:'Players',render:r=><span>{r.player1_username||'—'} vs {r.player2_username||'—'}</span>},{key:'match_type',label:'Game'},{key:'selected_map',label:'Map'},{key:'server',label:'Server'},{key:'score',label:'Score',render:r=><span>{r.score_p1 == null || r.score_p2 == null ? '—' : `${r.score_p1} : ${r.score_p2}`}</span>},{key:'status',label:'Status',render:status('status')},{key:'started_at',label:'Start time'}],
  reports:[{key:'reported_username',label:'Reported user'},{key:'reporter_username',label:'Reporter'},{key:'reason',label:'Reason'},{key:'status',label:'Status',render:status('status')},{key:'created_at',label:'Submitted'}],
  bans:[{key:'username',label:'Player'},{key:'reason',label:'Reason'},{key:'ban_type',label:'Type'},{key:'is_active',label:'Status',render:r=><AdminStatusBadge value={r.is_active?'active':'lifted'}/>},{key:'expires_at',label:'Expires'},{key:'issued_by_username',label:'Issued by'}],
  logs:[{key:'admin_username',label:'Admin'},{key:'action',label:'Action'},{key:'target_type',label:'Target type'},{key:'target_id',label:'Target ID'},{key:'ip',label:'IP'},{key:'created_at',label:'Timestamp'}],
  vip:[{key:'username',label:'User'},{key:'email',label:'Email'},{key:'is_premium',label:'VIP',render:r=><AdminStatusBadge value={r.is_premium?'active':'standard'}/>},{key:'vip_expires_at',label:'Expiration'},{key:'points',label:'Points'},{key:'last_seen',label:'Last seen'}],
  badges:[{key:'name',label:'Badge'},{key:'id',label:'ID'},{key:'rarity',label:'Rarity',render:status('rarity')},{key:'price_points',label:'Price'},{key:'featured',label:'Featured',render:status('featured')}],
  frames:[{key:'name',label:'Frame'},{key:'id',label:'ID'},{key:'rarity',label:'Rarity',render:status('rarity')},{key:'price_points',label:'Price'},{key:'featured',label:'Featured',render:status('featured')}],
}

export function AdminTable({section,rows,onSelect,onUserAction,onServerAction,page,total,limit,onPage}:{section:AdminSection;rows:AdminRow[];onSelect?:(r:AdminRow)=>void;onUserAction?:(r:AdminRow,a:AdminUserAction)=>void;onServerAction?:(r:AdminRow,a:AdminServerAction)=>void;page:number;total?:number;limit?:number;onPage:(p:number)=>void}) {
  const [sort,setSort]=useState('');const [direction,setDirection]=useState<'asc'|'desc'>('asc');const [filter,setFilter]=useState(section==='users'?'active':'all')
  useEffect(()=>setFilter(section==='users'?'active':'all'),[section])
  const cols=columns[section]||Object.keys(rows[0]||{}).filter(k=>!['details','social_links','owned_badges','owned_frames'].includes(k)).slice(0,7).map(key=>({key,label:key.split('_').join(' ')}))
  const rowState=(row:AdminRow)=>section==='users'?(row.deleted_at?'deactivated':'active'):String(row.status??row.is_active??'').toLowerCase()
  const visible=useMemo(()=>{let list=filter==='all'?rows:rows.filter(r=>rowState(r)===filter);if(sort)list=[...list].sort((a,b)=>String(a[sort]??'').localeCompare(String(b[sort]??''),undefined,{numeric:true})*(direction==='asc'?1:-1));return list},[rows,filter,sort,direction,section])
  const meta=sectionMeta[section];const statuses=Array.from(new Set(rows.map(rowState).filter(Boolean)))
  const toggleSort=(key:string)=>{if(sort===key)setDirection(v=>v==='asc'?'desc':'asc');else{setSort(key);setDirection('asc')}}
  return <Card className="min-w-0 overflow-hidden border-orange-900/25 bg-[#101011]"><CardHeader className="flex-row items-start justify-between gap-4 border-b border-orange-900/20 p-5"><div><CardTitle className="text-base text-slate-100">{meta.title}</CardTitle><CardDescription className="mt-1 text-xs">{meta.description} · {total??rows.length} records</CardDescription></div>{statuses.length>0&&<Select value={filter} onValueChange={setFilter}><SelectTrigger className="h-9 w-36 border-orange-900/30 bg-black/30 text-xs"><SelectValue placeholder="All statuses"/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{statuses.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>}</CardHeader>
    <CardContent className="p-0"><div className="max-w-full overflow-x-auto"><Table className="min-w-[880px]"><TableHeader className="sticky top-0 z-10 bg-[#151516]"><TableRow className="border-orange-900/20 hover:bg-transparent">{cols.map(c=><TableHead key={c.key} className="h-11 px-4 text-[10px] uppercase tracking-wider text-slate-500"><button className="flex items-center gap-1.5 hover:text-orange-300" onClick={()=>toggleSort(c.key)}>{c.label}<ArrowUpDown size={11}/></button></TableHead>)}<TableHead className="w-14"/></TableRow></TableHeader><TableBody>{visible.map((row,index)=><TableRow key={row.id||index} onDoubleClick={()=>onSelect?.(row)} className="h-14 border-orange-900/15 hover:bg-orange-500/[.04]">{cols.map(c=><TableCell key={c.key} className="max-w-64 px-4 text-xs text-slate-300"><div className="truncate">{c.render?c.render(row):formatAdminValue(row[c.key],c.key)}</div></TableCell>)}<TableCell className="px-3"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="size-8 text-slate-500 hover:text-orange-300"><MoreHorizontal size={16}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="border-orange-900/30 bg-[#121213]">{section==='users'&&onUserAction?<>{([['view','View details'],['edit','Edit user'],['points','Manage points'],['vip','Manage VIP'],['role','Manage role'],['badges','Manage badges'],['frames','Manage frames'],['ban',row.active_ban?'Unban user':'Ban / unban'],['deactivate',row.deleted_at?'Restore User':'Deactivate User'],['permanent','Permanently Delete User']] as [AdminUserAction,string][]).map(([action,label])=><DropdownMenuItem key={action} variant={(action==='deactivate'&&!row.deleted_at)||action==='permanent'?'destructive':'default'} onClick={()=>onUserAction(row,action)}>{label}</DropdownMenuItem>)}</>:section==='servers'&&onServerAction?<>{([['view','View details'],['edit','Edit server'],['status','Change status'],['assign','Assign match'],['unassign','Unassign match'],['copy','Copy connect command'],['delete','Delete server']] as [AdminServerAction,string][]).map(([action,label])=><DropdownMenuItem key={action} disabled={action==='unassign'&&!row.current_match_id} variant={action==='delete'?'destructive':'default'} onClick={()=>onServerAction(row,action)}>{label}</DropdownMenuItem>)}</>:<DropdownMenuItem onClick={()=>onSelect?.(row)}>View details</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}{!visible.length&&<TableRow><TableCell colSpan={cols.length+1} className="h-40 text-center text-sm text-slate-500">No records match this view.</TableCell></TableRow>}</TableBody></Table></div>
      <div className="flex min-h-14 items-center justify-between gap-4 border-t border-orange-900/20 px-5"><p className="text-xs text-slate-600">Showing {visible.length} of {total??rows.length}</p><div className="flex items-center gap-2"><Button variant="outline" size="icon" className="size-8 border-orange-900/30" disabled={page<=1} onClick={()=>onPage(page-1)}><ChevronLeft size={14}/></Button><span className="min-w-14 text-center text-xs text-slate-400">Page {page}</span><Button variant="outline" size="icon" className="size-8 border-orange-900/30" disabled={!limit||page*limit>=(total??rows.length)} onClick={()=>onPage(page+1)}><ChevronRight size={14}/></Button></div></div>
    </CardContent></Card>
}
