import { useEffect, useState } from 'react'
import { Loader2, MessageSquare, Send, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { communityAPI } from '../utils/api'
import { Button } from './ui/button'
import { Card,CardContent,CardHeader,CardTitle } from './ui/card'
import { Textarea } from './ui/textarea'

export function ProfileComments({profileUserId,currentUserId}:{profileUserId:string;currentUserId:string}){
  const [comments,setComments]=useState<any[]>([]),[loading,setLoading]=useState(true),[text,setText]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{let active=true;setLoading(true);communityAPI.getProfileComments(profileUserId).then((data:any)=>active&&setComments(Array.isArray(data.comments)?data.comments:[])).catch(reason=>active&&toast.error('Unable to load profile comments',{description:reason instanceof Error?reason.message:undefined})).finally(()=>active&&setLoading(false));return()=>{active=false}},[profileUserId])
  const submit=async()=>{if(!text.trim())return;setBusy(true);try{const data:any=await communityAPI.addProfileComment(profileUserId,text.trim());setComments(previous=>[data.comment,...previous]);setText('');toast.success('Profile comment posted')}catch(reason){toast.error('Unable to post profile comment',{description:reason instanceof Error?reason.message:undefined})}finally{setBusy(false)}}
  const remove=async(id:string)=>{try{await communityAPI.deleteProfileComment(id);setComments(previous=>previous.filter(comment=>comment.id!==id));toast.success('Profile comment removed')}catch(reason){toast.error('Unable to remove profile comment',{description:reason instanceof Error?reason.message:undefined})}}
  return <Card className="min-w-0 border-orange-900/20 bg-black/40"><CardHeader><CardTitle className="flex items-center gap-2 font-mono text-orange-400"><MessageSquare className="size-5"/>PROFILE COMMENTS</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-end gap-2"><Textarea aria-label="Profile comment" value={text} maxLength={1000} onChange={event=>setText(event.target.value)} placeholder="Leave a profile comment..." className="min-h-20"/><Button size="icon" aria-label="Post profile comment" disabled={busy||!text.trim()} onClick={()=>void submit()}>{busy?<Loader2 className="size-4 animate-spin"/>:<Send className="size-4"/>}</Button></div>{loading?<div className="flex justify-center py-8"><Loader2 className="size-5 animate-spin text-orange-400"/></div>:comments.length?<div className="space-y-3">{comments.map(comment=><div key={comment.id} className="flex gap-3 border border-orange-900/15 bg-black/25 p-3">{comment.author_avatar?<img src={comment.author_avatar} alt="" className="size-9 rounded object-cover"/>:<div className="size-9 shrink-0 rounded bg-orange-950/40"/>}<div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate font-mono text-xs text-orange-300">{comment.author_name}</p>{(String(comment.author_user_id)===String(currentUserId)||String(profileUserId)===String(currentUserId))&&<Button size="icon" variant="ghost" aria-label="Delete profile comment" onClick={()=>void remove(comment.id)}><Trash2 className="size-4"/></Button>}</div><p className="mt-1 whitespace-pre-wrap break-words text-sm text-gray-300">{comment.content}</p><p className="mt-2 text-[11px] text-gray-600">{new Date(comment.created_at).toLocaleString()}</p></div></div>)}</div>:<p className="py-8 text-center font-mono text-xs text-gray-500">NO PROFILE COMMENTS YET</p>}</CardContent></Card>
}
